/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_z_._tintas;

/**
 *
 * @author m.targa
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu_Button_Clientes = new javax.swing.JButton();
        Menu_Button_Catalogo = new javax.swing.JButton();
        Menu_Button_Estoque = new javax.swing.JButton();
        Menu_Button_Funcionario = new javax.swing.JButton();
        Menu_Button_Vendas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Menu_Button_Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU_PRINCIPAL");
        setPreferredSize(new java.awt.Dimension(1440, 1024));

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setLayout(null);

        Menu_Button_Clientes.setBackground(new java.awt.Color(7, 25, 82));
        Menu_Button_Clientes.setForeground(new java.awt.Color(7, 25, 82));
        Menu_Button_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projeto_z_/_tintas/botãoCliente.png"))); // NOI18N
        Menu_Button_Clientes.setBorder(null);
        Menu_Button_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Button_ClientesActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Button_Clientes);
        Menu_Button_Clientes.setBounds(70, 271, 400, 210);

        Menu_Button_Catalogo.setBackground(new java.awt.Color(7, 25, 82));
        Menu_Button_Catalogo.setForeground(new java.awt.Color(7, 25, 82));
        Menu_Button_Catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projeto_z_/_tintas/botãoCatálogo.png"))); // NOI18N
        Menu_Button_Catalogo.setBorder(null);
        Menu_Button_Catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Button_CatalogoActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Button_Catalogo);
        Menu_Button_Catalogo.setBounds(520, 271, 400, 210);

        Menu_Button_Estoque.setBackground(new java.awt.Color(7, 25, 82));
        Menu_Button_Estoque.setForeground(new java.awt.Color(7, 25, 82));
        Menu_Button_Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projeto_z_/_tintas/botãoEstoque.png"))); // NOI18N
        Menu_Button_Estoque.setBorder(null);
        jPanel1.add(Menu_Button_Estoque);
        Menu_Button_Estoque.setBounds(970, 271, 400, 210);

        Menu_Button_Funcionario.setBackground(new java.awt.Color(7, 25, 82));
        Menu_Button_Funcionario.setForeground(new java.awt.Color(7, 25, 82));
        Menu_Button_Funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botãoFuncionário.png"))); // NOI18N
        Menu_Button_Funcionario.setBorder(null);
        jPanel1.add(Menu_Button_Funcionario);
        Menu_Button_Funcionario.setBounds(295, 531, 400, 210);

        Menu_Button_Vendas.setBackground(new java.awt.Color(7, 25, 82));
        Menu_Button_Vendas.setForeground(new java.awt.Color(7, 25, 82));
        Menu_Button_Vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botãoVendas.png"))); // NOI18N
        Menu_Button_Vendas.setBorder(null);
        jPanel1.add(Menu_Button_Vendas);
        Menu_Button_Vendas.setBounds(745, 531, 400, 210);

        jLabel1.setBackground(new java.awt.Color(7, 25, 82));
        jLabel1.setForeground(new java.awt.Color(7, 25, 82));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botãoMenu.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 225, 95);

        jLabel2.setBackground(new java.awt.Color(7, 25, 82));
        jLabel2.setForeground(new java.awt.Color(7, 25, 82));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO_PINCEL.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1265, 25, 150, 150);

        Menu_Button_Sair.setBackground(new java.awt.Color(7, 25, 82));
        Menu_Button_Sair.setForeground(new java.awt.Color(7, 25, 82));
        Menu_Button_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botãoSair.png"))); // NOI18N
        Menu_Button_Sair.setText("jButton6");
        Menu_Button_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Button_SairActionPerformed(evt);
            }
        });
        jPanel1.add(Menu_Button_Sair);
        Menu_Button_Sair.setBounds(25, 924, 90, 75);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_Button_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Button_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_Button_ClientesActionPerformed

    private void Menu_Button_CatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Button_CatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_Button_CatalogoActionPerformed

    private void Menu_Button_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Button_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_Button_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menu_Button_Catalogo;
    private javax.swing.JButton Menu_Button_Clientes;
    private javax.swing.JButton Menu_Button_Estoque;
    private javax.swing.JButton Menu_Button_Funcionario;
    private javax.swing.JButton Menu_Button_Sair;
    private javax.swing.JButton Menu_Button_Vendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
