/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author Matheus
 */
public class TELA_ESTOQUE extends javax.swing.JFrame {

    /**
     * Creates new form TELA_ESTOQUE
     */
    public TELA_ESTOQUE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_estoque_consultar = new javax.swing.JButton();
        bt_estoque_cadastrar = new javax.swing.JButton();
        bt_estoque_voltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estoque titulo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 286, 88);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO_MENU.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1265, 25, 150, 150);

        bt_estoque_consultar.setBackground(new java.awt.Color(7, 25, 82));
        bt_estoque_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bt_consultar_item.png"))); // NOI18N
        bt_estoque_consultar.setBorder(null);
        jPanel1.add(bt_estoque_consultar);
        bt_estoque_consultar.setBounds(115, 330, 700, 160);

        bt_estoque_cadastrar.setBackground(new java.awt.Color(7, 25, 82));
        bt_estoque_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastrar novo item.png"))); // NOI18N
        bt_estoque_cadastrar.setBorder(null);
        jPanel1.add(bt_estoque_cadastrar);
        bt_estoque_cadastrar.setBounds(115, 540, 700, 160);

        bt_estoque_voltar.setBackground(new java.awt.Color(7, 25, 82));
        bt_estoque_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/voltarr.png"))); // NOI18N
        bt_estoque_voltar.setBorder(null);
        jPanel1.add(bt_estoque_voltar);
        bt_estoque_voltar.setBounds(31, 900, 75, 75);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG mulherLata.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(830, 262, 500, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_ESTOQUE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_estoque_cadastrar;
    private javax.swing.JButton bt_estoque_consultar;
    private javax.swing.JButton bt_estoque_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
