/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author f.martins
 */
public class Tela_Cliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela_Cliente.class.getName());

    /**
     * Creates new form Tela_Cliente
     */
    public Tela_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setForeground(new java.awt.Color(7, 25, 82));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(7, 25, 82));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(235, 244, 246));
        jTextField1.setMaximumSize(new java.awt.Dimension(400, 60));
        jTextField1.setMinimumSize(new java.awt.Dimension(400, 60));
        jTextField1.setPreferredSize(new java.awt.Dimension(400, 60));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(839, 524, 400, 60);

        jTextField2.setBackground(new java.awt.Color(7, 25, 82));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(235, 244, 246));
        jTextField2.setMaximumSize(new java.awt.Dimension(400, 60));
        jTextField2.setMinimumSize(new java.awt.Dimension(400, 60));
        jTextField2.setPreferredSize(new java.awt.Dimension(400, 60));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(839, 412, 400, 60);

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(7, 25, 82));
        jLabel6.setText("Senha");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(839, 490, 71, 30);

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(7, 25, 82));
        jLabel7.setText("Esqueceu sua senha?");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1073, 584, 170, 20);

        jButton2.setBackground(new java.awt.Color(235, 244, 246));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotãoEntrar (3).png"))); // NOI18N
        jButton2.setBorder(null);
        jPanel1.add(jButton2);
        jButton2.setBounds(830, 640, 420, 68);

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(7, 25, 82));
        jLabel8.setText("Matrícula");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(839, 380, 120, 30);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 25, 82));
        jLabel2.setText("Login");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(970, 250, 160, 100);

        jLabel1.setBackground(new java.awt.Color(7, 25, 82));
        jLabel1.setForeground(new java.awt.Color(7, 25, 82));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bemVindo.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(554, 216));
        jLabel1.setMinimumSize(new java.awt.Dimension(554, 216));
        jLabel1.setPreferredSize(new java.awt.Dimension(554, 216));
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(101, 160, 1417, 216);

        jLabel5.setBackground(new java.awt.Color(7, 25, 82));
        jLabel5.setForeground(new java.awt.Color(7, 25, 82));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Img esfera login.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(978, 107, 137, 130);

        jLabel4.setBackground(new java.awt.Color(7, 25, 82));
        jLabel4.setForeground(new java.awt.Color(7, 25, 82));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retangulo_tela_login.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(757, 107, 571, 850);

        jLabel3.setBackground(new java.awt.Color(7, 25, 82));
        jLabel3.setForeground(new java.awt.Color(7, 25, 82));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagem_Login.png"))); // NOI18N
        jLabel3.setAlignmentX(106.0F);
        jLabel3.setAlignmentY(412.0F);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(106, 412, 506, 506);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela_Cliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
