/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author m.targa
 */
public class TELA_CLIENTES extends javax.swing.JFrame {

    /**
     * Creates new form TELA_CLIENTES
     */
    public TELA_CLIENTES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bt_Clientes_Principal_Cadastrar = new javax.swing.JButton();
        Bt_Clientes_Principal_Consultar = new javax.swing.JButton();
        Bt_Clientes_Principal_Exibir = new javax.swing.JButton();
        Botao_Clientes_Principal_Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/InfoClientes.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 289, 89);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO_MENU.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1265, 25, 150, 150);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG Carrinho_Clientes.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(780, 217, 590, 590);

        Bt_Clientes_Principal_Cadastrar.setBackground(new java.awt.Color(7, 25, 82));
        Bt_Clientes_Principal_Cadastrar.setForeground(new java.awt.Color(7, 25, 82));
        Bt_Clientes_Principal_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bt_NovoCliente.png"))); // NOI18N
        Bt_Clientes_Principal_Cadastrar.setBorder(null);
        Bt_Clientes_Principal_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Clientes_Principal_CadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(Bt_Clientes_Principal_Cadastrar);
        Bt_Clientes_Principal_Cadastrar.setBounds(70, 236, 700, 160);

        Bt_Clientes_Principal_Consultar.setBackground(new java.awt.Color(7, 25, 82));
        Bt_Clientes_Principal_Consultar.setForeground(new java.awt.Color(7, 25, 82));
        Bt_Clientes_Principal_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bt_ConsulCadastro.png"))); // NOI18N
        Bt_Clientes_Principal_Consultar.setBorder(null);
        Bt_Clientes_Principal_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Clientes_Principal_ConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(Bt_Clientes_Principal_Consultar);
        Bt_Clientes_Principal_Consultar.setBounds(70, 430, 700, 160);

        Bt_Clientes_Principal_Exibir.setBackground(new java.awt.Color(7, 25, 82));
        Bt_Clientes_Principal_Exibir.setForeground(new java.awt.Color(7, 25, 82));
        Bt_Clientes_Principal_Exibir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bt_exibirCadastro.png"))); // NOI18N
        Bt_Clientes_Principal_Exibir.setBorder(null);
        Bt_Clientes_Principal_Exibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Clientes_Principal_ExibirActionPerformed(evt);
            }
        });
        jPanel1.add(Bt_Clientes_Principal_Exibir);
        Bt_Clientes_Principal_Exibir.setBounds(70, 656, 700, 160);

        Botao_Clientes_Principal_Sair.setBackground(new java.awt.Color(7, 25, 82));
        Botao_Clientes_Principal_Sair.setForeground(new java.awt.Color(7, 25, 82));
        Botao_Clientes_Principal_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botãoSair.png"))); // NOI18N
        Botao_Clientes_Principal_Sair.setBorder(null);
        jPanel1.add(Botao_Clientes_Principal_Sair);
        Botao_Clientes_Principal_Sair.setBounds(25, 900, 75, 75);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_Clientes_Principal_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Clientes_Principal_CadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_Clientes_Principal_CadastrarActionPerformed

    private void Bt_Clientes_Principal_ExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Clientes_Principal_ExibirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_Clientes_Principal_ExibirActionPerformed

    private void Bt_Clientes_Principal_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Clientes_Principal_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_Clientes_Principal_ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_CLIENTES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Clientes_Principal_Sair;
    private javax.swing.JButton Bt_Clientes_Principal_Cadastrar;
    private javax.swing.JButton Bt_Clientes_Principal_Consultar;
    private javax.swing.JButton Bt_Clientes_Principal_Exibir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
