/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author m.targa
 */
public class TELA_CLIENTES_CONSULTAR_CAD extends javax.swing.JFrame {

    /**
     * Creates new form TELA_CLIENTES_CONSULTAR_CAD
     */
    public TELA_CLIENTES_CONSULTAR_CAD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_voltar_cliente = new javax.swing.JButton();
        bt_busca_cliente = new javax.swing.JButton();
        Cliente_Busca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        Cliente_CPFCNPJ = new javax.swing.JTextField();
        Cliente_telefone = new javax.swing.JTextField();
        Cliente_dt_nasc = new javax.swing.JTextField();
        Cliente_CEP = new javax.swing.JTextField();
        Cliente_Cidade = new javax.swing.JTextField();
        Cliente_Rua = new javax.swing.JTextField();
        Cliente_UF = new javax.swing.JTextField();
        Cliente_Bairro = new javax.swing.JTextField();
        Cliente_Numero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bt_editar_cliente = new javax.swing.JButton();
        bt_excluir_cliente = new javax.swing.JButton();
        bt_salvar_alt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO_MENU.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1265, 45, 150, 150);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Identificador consultar cadastro.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(31, 26, 520, 88);

        bt_voltar_cliente.setBackground(new java.awt.Color(7, 25, 82));
        bt_voltar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/voltarr.png"))); // NOI18N
        bt_voltar_cliente.setBorder(null);
        jPanel1.add(bt_voltar_cliente);
        bt_voltar_cliente.setBounds(25, 900, 53, 54);

        bt_busca_cliente.setBackground(new java.awt.Color(235, 244, 246));
        bt_busca_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botao_buscar_cons_cad.png"))); // NOI18N
        bt_busca_cliente.setBorder(null);
        jPanel1.add(bt_busca_cliente);
        bt_busca_cliente.setBounds(856, 227, 320, 60);

        Cliente_Busca.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Busca.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Busca.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Busca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Cliente_Busca);
        Cliente_Busca.setBounds(144, 257, 400, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BUSCA_CLIENTES.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 205, 1184, 104);

        jTextField2.setText("jTextField1");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(180, 270, 71, 22);

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(144, 257, 400, 40);

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(144, 257, 400, 40);

        Cliente_CPFCNPJ.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_CPFCNPJ.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_CPFCNPJ.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_CPFCNPJ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Cliente_CPFCNPJ);
        Cliente_CPFCNPJ.setBounds(144, 408, 400, 40);

        Cliente_telefone.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_telefone.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_telefone.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Cliente_telefone);
        Cliente_telefone.setBounds(834, 408, 400, 40);

        Cliente_dt_nasc.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_dt_nasc.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_dt_nasc.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_dt_nasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Cliente_dt_nasc);
        Cliente_dt_nasc.setBounds(144, 505, 400, 40);

        Cliente_CEP.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_CEP.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_CEP.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_CEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Cliente_CEP);
        Cliente_CEP.setBounds(144, 666, 320, 40);

        Cliente_Cidade.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cidade.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cidade.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Cliente_Cidade);
        Cliente_Cidade.setBounds(144, 769, 320, 40);

        Cliente_Rua.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Rua.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Rua.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Rua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Cliente_Rua);
        Cliente_Rua.setBounds(539, 666, 320, 40);

        Cliente_UF.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_UF.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_UF.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_UF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Cliente_UF);
        Cliente_UF.setBounds(539, 769, 320, 40);

        Cliente_Bairro.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Bairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cliente_Bairro.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Bairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Cliente_Bairro);
        Cliente_Bairro.setBounds(934, 662, 320, 40);

        Cliente_Numero.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Numero.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Numero.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Numero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(Cliente_Numero);
        Cliente_Numero.setBounds(940, 769, 320, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CAMPO_CADASTRO_CLIENTES.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 339, 1184, 527);

        bt_editar_cliente.setBackground(new java.awt.Color(7, 25, 82));
        bt_editar_cliente.setForeground(new java.awt.Color(7, 25, 82));
        bt_editar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotaoEditar.png"))); // NOI18N
        bt_editar_cliente.setBorder(null);
        jPanel1.add(bt_editar_cliente);
        bt_editar_cliente.setBounds(220, 906, 320, 60);

        bt_excluir_cliente.setBackground(new java.awt.Color(7, 25, 82));
        bt_excluir_cliente.setForeground(new java.awt.Color(7, 25, 82));
        bt_excluir_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botaoexluir.png"))); // NOI18N
        bt_excluir_cliente.setBorder(null);
        jPanel1.add(bt_excluir_cliente);
        bt_excluir_cliente.setBounds(834, 906, 320, 60);

        bt_salvar_alt.setBackground(new java.awt.Color(7, 25, 82));
        bt_salvar_alt.setForeground(new java.awt.Color(7, 25, 82));
        bt_salvar_alt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vetor salvar.png"))); // NOI18N
        bt_salvar_alt.setBorder(null);
        jPanel1.add(bt_salvar_alt);
        bt_salvar_alt.setBounds(1364, 900, 53, 54);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES_CONSULTAR_CAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES_CONSULTAR_CAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES_CONSULTAR_CAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES_CONSULTAR_CAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_CLIENTES_CONSULTAR_CAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cliente_Bairro;
    private javax.swing.JTextField Cliente_Busca;
    private javax.swing.JTextField Cliente_CEP;
    private javax.swing.JTextField Cliente_CPFCNPJ;
    private javax.swing.JTextField Cliente_Cidade;
    private javax.swing.JTextField Cliente_Numero;
    private javax.swing.JTextField Cliente_Rua;
    private javax.swing.JTextField Cliente_UF;
    private javax.swing.JTextField Cliente_dt_nasc;
    private javax.swing.JTextField Cliente_telefone;
    private javax.swing.JButton bt_busca_cliente;
    private javax.swing.JButton bt_editar_cliente;
    private javax.swing.JButton bt_excluir_cliente;
    private javax.swing.JButton bt_salvar_alt;
    private javax.swing.JButton bt_voltar_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
