/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author m.targa
 */
public class TELA_CLIENTES_CADASTRO extends javax.swing.JFrame {

    /**
     * Creates new form TELA_CLIENTES_CADASTRO
     */
    public TELA_CLIENTES_CADASTRO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cliente_Cadastro_UF = new javax.swing.JTextField();
        Cliente_Cadastro_Numero = new javax.swing.JTextField();
        Cliente_Cadastro_Rua = new javax.swing.JTextField();
        Cliente_Cadastro_CPFCNPJ = new javax.swing.JTextField();
        Cliente_Cadastro_Email = new javax.swing.JTextField();
        Cliente_Cadastro_telefone = new javax.swing.JTextField();
        Cliente_Cadastro_CEP = new javax.swing.JTextField();
        Cliente_Cadastro_Nome = new javax.swing.JTextField();
        Cliente_Cadastro_Bairro = new javax.swing.JTextField();
        Cliente_Cadastro_Cidade = new javax.swing.JTextField();
        Cliente_Cadastro_dtnasc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cliente_Cadastro_Voltar = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        Cliente_Cadastro_Salvar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setLayout(null);

        Cliente_Cadastro_UF.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_UF.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_UF.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_UF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_UFActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_UF);
        Cliente_Cadastro_UF.setBounds(550, 750, 350, 45);

        Cliente_Cadastro_Numero.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_Numero.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_Numero.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_Numero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_NumeroActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_Numero);
        Cliente_Cadastro_Numero.setBounds(950, 750, 240, 45);

        Cliente_Cadastro_Rua.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_Rua.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_Rua.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_Rua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_Rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_RuaActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_Rua);
        Cliente_Cadastro_Rua.setBounds(550, 660, 350, 45);

        Cliente_Cadastro_CPFCNPJ.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_CPFCNPJ.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_CPFCNPJ.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_CPFCNPJ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_CPFCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_CPFCNPJActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_CPFCNPJ);
        Cliente_Cadastro_CPFCNPJ.setBounds(150, 370, 500, 45);

        Cliente_Cadastro_Email.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_Email.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_Email.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_Email);
        Cliente_Cadastro_Email.setBounds(800, 370, 500, 45);

        Cliente_Cadastro_telefone.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_telefone.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_telefone.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_telefoneActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_telefone);
        Cliente_Cadastro_telefone.setBounds(150, 470, 500, 45);

        Cliente_Cadastro_CEP.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_CEP.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_CEP.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_CEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_CEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_CEPActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_CEP);
        Cliente_Cadastro_CEP.setBounds(150, 660, 350, 45);

        Cliente_Cadastro_Nome.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_Nome.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_Nome.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_Nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_NomeActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_Nome);
        Cliente_Cadastro_Nome.setBounds(150, 280, 500, 45);

        Cliente_Cadastro_Bairro.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_Bairro.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_Bairro.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_Bairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_Bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_BairroActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_Bairro);
        Cliente_Cadastro_Bairro.setBounds(950, 660, 350, 45);

        Cliente_Cadastro_Cidade.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_Cidade.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_Cidade.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_Cidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_CidadeActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_Cidade);
        Cliente_Cadastro_Cidade.setBounds(150, 750, 350, 45);

        Cliente_Cadastro_dtnasc.setBackground(new java.awt.Color(25, 59, 122));
        Cliente_Cadastro_dtnasc.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        Cliente_Cadastro_dtnasc.setForeground(new java.awt.Color(235, 244, 246));
        Cliente_Cadastro_dtnasc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cliente_Cadastro_dtnasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cliente_Cadastro_dtnascActionPerformed(evt);
            }
        });
        jPanel1.add(Cliente_Cadastro_dtnasc);
        Cliente_Cadastro_dtnasc.setBounds(800, 280, 500, 45);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastrar novo cliente LOGO.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 620, 89);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO_MENU.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1265, 25, 150, 150);

        Cliente_Cadastro_Voltar.setBackground(new java.awt.Color(7, 25, 82));
        Cliente_Cadastro_Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/voltarr.png"))); // NOI18N
        Cliente_Cadastro_Voltar.setBorder(null);
        jPanel1.add(Cliente_Cadastro_Voltar);
        Cliente_Cadastro_Voltar.setBounds(25, 900, 75, 75);

        jToggleButton2.setBackground(new java.awt.Color(7, 25, 82));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vetor salvar.png"))); // NOI18N
        jToggleButton2.setBorder(null);
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(1340, 900, 75, 75);

        Cliente_Cadastro_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Campos_Info.png"))); // NOI18N
        Cliente_Cadastro_Salvar.setText("jLabel3");
        Cliente_Cadastro_Salvar.setMaximumSize(new java.awt.Dimension(1440, 1024));
        Cliente_Cadastro_Salvar.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.add(Cliente_Cadastro_Salvar);
        Cliente_Cadastro_Salvar.setBounds(75, 174, 1290, 676);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cliente_Cadastro_dtnascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_dtnascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_dtnascActionPerformed

    private void Cliente_Cadastro_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_NomeActionPerformed

    private void Cliente_Cadastro_CPFCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_CPFCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_CPFCNPJActionPerformed

    private void Cliente_Cadastro_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_EmailActionPerformed

    private void Cliente_Cadastro_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_telefoneActionPerformed

    private void Cliente_Cadastro_CEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_CEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_CEPActionPerformed

    private void Cliente_Cadastro_RuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_RuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_RuaActionPerformed

    private void Cliente_Cadastro_BairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_BairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_BairroActionPerformed

    private void Cliente_Cadastro_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_NumeroActionPerformed

    private void Cliente_Cadastro_UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_UFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_UFActionPerformed

    private void Cliente_Cadastro_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cliente_Cadastro_CidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cliente_Cadastro_CidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTES_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_CLIENTES_CADASTRO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cliente_Cadastro_Bairro;
    private javax.swing.JTextField Cliente_Cadastro_CEP;
    private javax.swing.JTextField Cliente_Cadastro_CPFCNPJ;
    private javax.swing.JTextField Cliente_Cadastro_Cidade;
    private javax.swing.JTextField Cliente_Cadastro_Email;
    private javax.swing.JTextField Cliente_Cadastro_Nome;
    private javax.swing.JTextField Cliente_Cadastro_Numero;
    private javax.swing.JTextField Cliente_Cadastro_Rua;
    private javax.swing.JLabel Cliente_Cadastro_Salvar;
    private javax.swing.JTextField Cliente_Cadastro_UF;
    private javax.swing.JToggleButton Cliente_Cadastro_Voltar;
    private javax.swing.JTextField Cliente_Cadastro_dtnasc;
    private javax.swing.JTextField Cliente_Cadastro_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
