/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author Gabriel
 */
public class TELA_LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form TELA_LOGIN
     */
    public TELA_LOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        senha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ENTRAR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 244, 246));
        jLabel3.setText("Bem-vindo ao");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 160, 400, 80);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 244, 246));
        jLabel1.setText("Z-Tintas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 230, 240, 80);

        matricula.setBackground(new java.awt.Color(7, 25, 82));
        matricula.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula.setForeground(new java.awt.Color(235, 244, 246));
        matricula.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });
        jPanel1.add(matricula);
        matricula.setBounds(839, 412, 400, 60);

        senha.setBackground(new java.awt.Color(7, 25, 82));
        senha.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        senha.setForeground(new java.awt.Color(235, 244, 246));
        senha.setMaximumSize(new java.awt.Dimension(400, 60));
        senha.setMinimumSize(new java.awt.Dimension(400, 60));
        senha.setPreferredSize(new java.awt.Dimension(400, 60));
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        jPanel1.add(senha);
        senha.setBounds(839, 524, 400, 60);

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(7, 25, 82));
        jLabel7.setText("Esqueceu sua senha?");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(1073, 584, 170, 20);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 25, 82));
        jLabel2.setText("Login");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(970, 250, 160, 100);

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(7, 25, 82));
        jLabel8.setText("Matrícula");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(839, 380, 120, 30);

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(7, 25, 82));
        jLabel6.setText("Senha");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(839, 490, 71, 30);

        ENTRAR.setBackground(new java.awt.Color(7, 25, 82));
        ENTRAR.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        ENTRAR.setText("ENTRAR");
        ENTRAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTRARActionPerformed(evt);
            }
        });
        jPanel1.add(ENTRAR);
        ENTRAR.setBounds(840, 625, 400, 60);

        jPanel2.setBackground(new java.awt.Color(235, 244, 246));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(757, 158, 571, 700);

        jLabel4.setBackground(new java.awt.Color(7, 25, 82));
        jLabel4.setForeground(new java.awt.Color(7, 25, 82));
        jLabel4.setAlignmentX(106.0F);
        jLabel4.setAlignmentY(412.0F);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(106, 412, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void ENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTRARActionPerformed
        TELA_MENU_PRINCIPAL menu = new TELA_MENU_PRINCIPAL();
        menu.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_ENTRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ENTRAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField senha;
    // End of variables declaration//GEN-END:variables
}
