/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JColorChooser;
import com.mycompany.z_tintas.Classe_produto;
import static com.mycompany.z_tintas.Classe_produto.inserirProduto;
import javax.swing.JOptionPane;

/**
 *
 * @author m.targa
 */
public class TELA_ESTOQUE_CADASTRO extends javax.swing.JFrame {

    /**
     * Creates new form TELA_ESTOQUE_CADASTRO
     */
    public TELA_ESTOQUE_CADASTRO() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Preco = new javax.swing.JTextField();
        NomeProduto = new javax.swing.JTextField();
        MarcaProduto = new javax.swing.JTextField();
        Cadastrar_produto = new javax.swing.JButton();
        Escolher_cor = new javax.swing.JColorChooser();
        jLabel18 = new javax.swing.JLabel();
        CodHex = new javax.swing.JTextField();
        Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(235, 244, 246));
        jPanel2.setMaximumSize(new java.awt.Dimension(1138, 593));
        jPanel2.setMinimumSize(new java.awt.Dimension(1138, 593));
        jPanel2.setPreferredSize(new java.awt.Dimension(1138, 593));
        jPanel2.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(7, 25, 82));
        jLabel16.setText("PREÇO R$:");
        jLabel16.setToolTipText("");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(320, 150, 140, 30);

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(7, 25, 82));
        jLabel15.setText("NOME");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(30, 30, 80, 30);

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(7, 25, 82));
        jLabel12.setText("MARCA");
        jLabel12.setToolTipText("");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(320, 30, 100, 30);

        Preco.setBackground(new java.awt.Color(7, 25, 82));
        Preco.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        Preco.setForeground(new java.awt.Color(235, 244, 246));
        Preco.setMaximumSize(new java.awt.Dimension(400, 60));
        Preco.setMinimumSize(new java.awt.Dimension(400, 60));
        Preco.setPreferredSize(new java.awt.Dimension(400, 60));
        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });
        jPanel2.add(Preco);
        Preco.setBounds(320, 190, 200, 60);

        NomeProduto.setBackground(new java.awt.Color(7, 25, 82));
        NomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        NomeProduto.setForeground(new java.awt.Color(235, 244, 246));
        NomeProduto.setMaximumSize(new java.awt.Dimension(400, 60));
        NomeProduto.setMinimumSize(new java.awt.Dimension(400, 60));
        NomeProduto.setPreferredSize(new java.awt.Dimension(400, 60));
        NomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(NomeProduto);
        NomeProduto.setBounds(30, 70, 250, 60);

        MarcaProduto.setBackground(new java.awt.Color(7, 25, 82));
        MarcaProduto.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        MarcaProduto.setForeground(new java.awt.Color(235, 244, 246));
        MarcaProduto.setMaximumSize(new java.awt.Dimension(400, 60));
        MarcaProduto.setMinimumSize(new java.awt.Dimension(400, 60));
        MarcaProduto.setPreferredSize(new java.awt.Dimension(400, 60));
        MarcaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(MarcaProduto);
        MarcaProduto.setBounds(320, 70, 200, 60);

        Cadastrar_produto.setBackground(new java.awt.Color(7, 25, 82));
        Cadastrar_produto.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Cadastrar_produto.setForeground(new java.awt.Color(235, 244, 246));
        Cadastrar_produto.setText("CADASTRAR PRODUTO");
        Cadastrar_produto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cadastrar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_produtoActionPerformed(evt);
            }
        });
        jPanel2.add(Cadastrar_produto);
        Cadastrar_produto.setBounds(100, 330, 310, 50);
        jPanel2.add(Escolher_cor);
        Escolher_cor.setBounds(530, 140, 590, 320);

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(7, 25, 82));
        jLabel18.setText("CÓDIGO HEX");
        jLabel18.setToolTipText("");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(30, 150, 160, 30);

        CodHex.setBackground(new java.awt.Color(7, 25, 82));
        CodHex.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        CodHex.setForeground(new java.awt.Color(235, 244, 246));
        CodHex.setMaximumSize(new java.awt.Dimension(400, 60));
        CodHex.setMinimumSize(new java.awt.Dimension(400, 60));
        CodHex.setPreferredSize(new java.awt.Dimension(400, 60));
        CodHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodHexActionPerformed(evt);
            }
        });
        jPanel2.add(CodHex);
        CodHex.setBounds(30, 190, 250, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(151, 151, 1138, 593);

        Voltar.setBackground(new java.awt.Color(7, 25, 82));
        Voltar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Voltar.setForeground(new java.awt.Color(235, 244, 246));
        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltarr.png"))); // NOI18N
        Voltar.setBorder(null);
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(Voltar);
        Voltar.setBounds(25, 900, 75, 75);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 244, 246));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Info_cadastrar_item estoque m.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(31, 26, 543, 77);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO ZTINTAS.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1265, 25, 150, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoActionPerformed

    private void NomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeProdutoActionPerformed

    private void MarcaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaProdutoActionPerformed

    private void Cadastrar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_produtoActionPerformed
        Classe_produto produto;
        String precoTexto = Preco.getText().replace(",", ".");
        double preco = Double.parseDouble(precoTexto);
        produto = new Classe_produto(NomeProduto.getText(),CodHex.getText(),
        MarcaProduto.getText()/*,Integer.parseInt(QuantidadeProduto.getText())*/,preco/*Double.parseDouble(Preco.getText())*/);
        boolean x1 = false;
        /*boolean x2 = false;*/
        /*boolean x3 = false;*/
        boolean x4 = false;
        boolean x5 = false;
        boolean x6 = false;
        
        
        try{
            if(NomeProduto.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "O CAMPO NOME É OBRIGATÓRIO!!!");
            }else{
                x1 = true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha na Inserção do nome!!!");
            e.printStackTrace();
        }
      /*  try{
            if(TamanhoProduto.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "O CAMPO TAMANHO É OBRIGATÓRIO!!!");
            }else{
                x2 = true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha na Inserção do TAMANHO!!!");
            e.printStackTrace();
        }*/
       /* try{
            if(QuantidadeProduto.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "O CAMPO QTD É OBRIGATÓRIO!!!");
            }else{
                x3 = true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha na Inserção da QTD!!!");
            e.printStackTrace();
        }*/
        try{
            if(MarcaProduto.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "O CAMPO MARCA É OBRIGATÓRIO!!!");
            }else{
                x4 = true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha na Inserção da MARCA!!!");
            e.printStackTrace();
        }
        try{
            if(CodHex.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "O CAMPO CODHEX É OBRIGATÓRIO!!!");
            }else{
                x5 = true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha na Inserção do CODHEX!!!");
            e.printStackTrace();
        }
        try{
            if(Preco.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "O CAMPO PRECO É OBRIGATÓRIO!!!");
            }else{
                x6 = true;
            }           
        }catch(NumberFormatException z){
            JOptionPane.showMessageDialog(null, "Falha na Inserção do PRECO!!!");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha na Inserção do PRECO!!!");
            e.printStackTrace();
        }       
        if(x1 /*&& x2 && x3*/ && x4 && x5 && x6){
            inserirProduto(produto);
        }
        
    }//GEN-LAST:event_Cadastrar_produtoActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        TELA_ESTOQUE_MENU estoque_menu = new TELA_ESTOQUE_MENU();               
        estoque_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void CodHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodHexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodHexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_ESTOQUE_CADASTRO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar_produto;
    private javax.swing.JTextField CodHex;
    private javax.swing.JColorChooser Escolher_cor;
    private javax.swing.JTextField MarcaProduto;
    private javax.swing.JTextField NomeProduto;
    private javax.swing.JTextField Preco;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
