/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author Gabriel
 */
public class TELA_MENU_PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form TELA_MENU_PRINCIPAL
     */
    public TELA_MENU_PRINCIPAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bt_cliente = new javax.swing.JButton();
        bt_catalogo = new javax.swing.JButton();
        bt_estoque = new javax.swing.JButton();
        bt_funcionario = new javax.swing.JButton();
        bt_vendas = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(7, 25, 82));
        jPanel2.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel2.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel2.setLayout(null);

        bt_cliente.setBackground(new java.awt.Color(7, 25, 82));
        bt_cliente.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        bt_cliente.setForeground(new java.awt.Color(7, 25, 82));
        bt_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botãoCliente f.png"))); // NOI18N
        bt_cliente.setBorder(null);
        bt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clienteActionPerformed(evt);
            }
        });
        jPanel2.add(bt_cliente);
        bt_cliente.setBounds(70, 277, 400, 220);

        bt_catalogo.setBackground(new java.awt.Color(7, 25, 82));
        bt_catalogo.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        bt_catalogo.setForeground(new java.awt.Color(7, 25, 82));
        bt_catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botãoCatálogo f.png"))); // NOI18N
        bt_catalogo.setBorder(null);
        bt_catalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_catalogoActionPerformed(evt);
            }
        });
        jPanel2.add(bt_catalogo);
        bt_catalogo.setBounds(520, 277, 400, 220);

        bt_estoque.setBackground(new java.awt.Color(7, 25, 82));
        bt_estoque.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        bt_estoque.setForeground(new java.awt.Color(7, 25, 82));
        bt_estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botãoEstoque f.png"))); // NOI18N
        bt_estoque.setBorder(null);
        bt_estoque.setPreferredSize(new java.awt.Dimension(400, 210));
        bt_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_estoqueActionPerformed(evt);
            }
        });
        jPanel2.add(bt_estoque);
        bt_estoque.setBounds(970, 277, 400, 220);

        bt_funcionario.setBackground(new java.awt.Color(7, 25, 82));
        bt_funcionario.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        bt_funcionario.setForeground(new java.awt.Color(7, 25, 82));
        bt_funcionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botãoFuncionário f.png"))); // NOI18N
        bt_funcionario.setBorder(null);
        bt_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_funcionarioActionPerformed(evt);
            }
        });
        jPanel2.add(bt_funcionario);
        bt_funcionario.setBounds(295, 537, 400, 220);

        bt_vendas.setBackground(new java.awt.Color(7, 25, 82));
        bt_vendas.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        bt_vendas.setForeground(new java.awt.Color(7, 25, 82));
        bt_vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botãoVendas f.png"))); // NOI18N
        bt_vendas.setToolTipText("");
        bt_vendas.setBorder(null);
        jPanel2.add(bt_vendas);
        bt_vendas.setBounds(745, 537, 410, 220);

        Excluir.setBackground(new java.awt.Color(7, 25, 82));
        Excluir.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Excluir.setForeground(new java.awt.Color(7, 25, 82));
        Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botãoSair f.png"))); // NOI18N
        Excluir.setBorder(null);
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(Excluir);
        Excluir.setBounds(25, 900, 90, 90);

        jLabel1.setBackground(new java.awt.Color(7, 25, 82));
        jLabel1.setForeground(new java.awt.Color(7, 25, 82));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botãoMenu f.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(25, 25, 230, 80);

        jLabel2.setBackground(new java.awt.Color(7, 25, 82));
        jLabel2.setForeground(new java.awt.Color(7, 25, 82));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO ZTINTAS.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(1265, 25, 150, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_catalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_catalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_catalogoActionPerformed

    private void bt_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_funcionarioActionPerformed
        TELA_FUNCIONARIO_MENU func_menu = new TELA_FUNCIONARIO_MENU();
        func_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_funcionarioActionPerformed

    private void bt_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_estoqueActionPerformed
        // TODO add your handling code here:
        TELA_ESTOQUE_MENU esto_menu = new TELA_ESTOQUE_MENU();
        esto_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_estoqueActionPerformed

    private void bt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clienteActionPerformed
        // TODO add your handling code here:
        TELA_CLIENTE_MENU clit_menu = new TELA_CLIENTE_MENU();
        clit_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_clienteActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_MENU_PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_MENU_PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Excluir;
    private javax.swing.JButton bt_catalogo;
    private javax.swing.JButton bt_cliente;
    private javax.swing.JButton bt_estoque;
    private javax.swing.JButton bt_funcionario;
    private javax.swing.JButton bt_vendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
