/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author Matheus
 */
public class TELA_CLIENTE_MENU extends javax.swing.JFrame {

    /**
     * Creates new form TELA_CLIENTE_MENU
     */
    public TELA_CLIENTE_MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CONSULTAR_CADASTROS = new javax.swing.JButton();
        CADASTRO_CLIENTE = new javax.swing.JButton();
        EXIBIR_CADASTROS = new javax.swing.JButton();
        BT_VOLTAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        CONSULTAR_CADASTROS.setBackground(new java.awt.Color(235, 244, 246));
        CONSULTAR_CADASTROS.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        CONSULTAR_CADASTROS.setForeground(new java.awt.Color(7, 25, 82));
        CONSULTAR_CADASTROS.setText("CONSULTAR CADASTRO");
        CONSULTAR_CADASTROS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(CONSULTAR_CADASTROS);
        CONSULTAR_CADASTROS.setBounds(67, 637, 700, 160);

        CADASTRO_CLIENTE.setBackground(new java.awt.Color(235, 244, 246));
        CADASTRO_CLIENTE.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        CADASTRO_CLIENTE.setForeground(new java.awt.Color(7, 25, 82));
        CADASTRO_CLIENTE.setText("CADASTRAR NOVO CLIENTE");
        CADASTRO_CLIENTE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(CADASTRO_CLIENTE);
        CADASTRO_CLIENTE.setBounds(67, 217, 700, 160);

        EXIBIR_CADASTROS.setBackground(new java.awt.Color(235, 244, 246));
        EXIBIR_CADASTROS.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        EXIBIR_CADASTROS.setForeground(new java.awt.Color(7, 25, 82));
        EXIBIR_CADASTROS.setText("EXIBIR CADASTROS");
        EXIBIR_CADASTROS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(EXIBIR_CADASTROS);
        EXIBIR_CADASTROS.setBounds(67, 427, 700, 160);

        BT_VOLTAR.setBackground(new java.awt.Color(7, 25, 82));
        BT_VOLTAR.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        BT_VOLTAR.setForeground(new java.awt.Color(235, 244, 246));
        BT_VOLTAR.setText("VOLTAR");
        BT_VOLTAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BT_VOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_VOLTARActionPerformed(evt);
            }
        });
        jPanel1.add(BT_VOLTAR);
        BT_VOLTAR.setBounds(25, 900, 150, 60);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 244, 246));
        jLabel1.setText("CLIENTES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 300, 62);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_VOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_VOLTARActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BT_VOLTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_CLIENTE_MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_VOLTAR;
    private javax.swing.JButton CADASTRO_CLIENTE;
    private javax.swing.JButton CONSULTAR_CADASTROS;
    private javax.swing.JButton EXIBIR_CADASTROS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
