/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author Matheus
 */
public class TELA_CLIENTE_CONSULTAR extends javax.swing.JFrame {

    /**
     * Creates new form TELA_CLIENTE_CONSULTAR
     */
    public TELA_CLIENTE_CONSULTAR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        matricula1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        matricula2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        matricula4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        matricula5 = new javax.swing.JTextField();
        matricula8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        matricula6 = new javax.swing.JTextField();
        matricula7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        matricula9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        matricula10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        matricula3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Procurar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(235, 244, 246));
        jPanel2.setLayout(null);

        matricula1.setBackground(new java.awt.Color(7, 25, 82));
        matricula1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula1.setForeground(new java.awt.Color(235, 244, 246));
        matricula1.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula1.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula1.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula1ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula1);
        matricula1.setBounds(520, 50, 400, 60);

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(7, 25, 82));
        jLabel9.setText("DATA DE NASCIMENTO");
        jLabel9.setToolTipText("");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(520, 20, 290, 30);

        matricula2.setBackground(new java.awt.Color(7, 25, 82));
        matricula2.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula2.setForeground(new java.awt.Color(235, 244, 246));
        matricula2.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula2.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula2.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula2ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula2);
        matricula2.setBounds(40, 150, 400, 60);

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(7, 25, 82));
        jLabel10.setText("CPF/CNPJ");
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 120, 120, 30);

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(7, 25, 82));
        jLabel8.setText("TELEFONE");
        jLabel8.setToolTipText("");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 220, 120, 30);

        matricula.setBackground(new java.awt.Color(7, 25, 82));
        matricula.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula.setForeground(new java.awt.Color(235, 244, 246));
        matricula.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });
        jPanel2.add(matricula);
        matricula.setBounds(40, 250, 400, 60);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 320, 1290, 20);

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(7, 25, 82));
        jLabel11.setText("ENDEREÇO");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 330, 140, 30);

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(7, 25, 82));
        jLabel13.setText("CEP");
        jLabel13.setToolTipText("");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(40, 370, 120, 30);

        matricula4.setBackground(new java.awt.Color(7, 25, 82));
        matricula4.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula4.setForeground(new java.awt.Color(235, 244, 246));
        matricula4.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula4.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula4.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula4ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula4);
        matricula4.setBounds(40, 400, 400, 60);

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(7, 25, 82));
        jLabel14.setText("CIDADE");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 470, 120, 30);

        matricula5.setBackground(new java.awt.Color(7, 25, 82));
        matricula5.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula5.setForeground(new java.awt.Color(235, 244, 246));
        matricula5.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula5.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula5.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula5ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula5);
        matricula5.setBounds(40, 500, 400, 60);

        matricula8.setBackground(new java.awt.Color(7, 25, 82));
        matricula8.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula8.setForeground(new java.awt.Color(235, 244, 246));
        matricula8.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula8.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula8.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula8ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula8);
        matricula8.setBounds(470, 500, 400, 60);

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(7, 25, 82));
        jLabel17.setText("BAIRRO");
        jLabel17.setToolTipText("");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(470, 470, 120, 30);

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(7, 25, 82));
        jLabel15.setText("RUA");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(470, 370, 120, 30);

        matricula6.setBackground(new java.awt.Color(7, 25, 82));
        matricula6.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula6.setForeground(new java.awt.Color(235, 244, 246));
        matricula6.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula6.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula6.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula6ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula6);
        matricula6.setBounds(470, 400, 400, 60);

        matricula7.setBackground(new java.awt.Color(7, 25, 82));
        matricula7.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula7.setForeground(new java.awt.Color(235, 244, 246));
        matricula7.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula7.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula7.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula7ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula7);
        matricula7.setBounds(900, 400, 150, 60);

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(7, 25, 82));
        jLabel16.setText("UF");
        jLabel16.setToolTipText("");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(900, 370, 120, 30);

        matricula9.setBackground(new java.awt.Color(7, 25, 82));
        matricula9.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula9.setForeground(new java.awt.Color(235, 244, 246));
        matricula9.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula9.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula9.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula9ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula9);
        matricula9.setBounds(900, 500, 150, 60);

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(7, 25, 82));
        jLabel18.setText("NÚMERO");
        jLabel18.setToolTipText("");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(900, 470, 120, 30);

        matricula10.setBackground(new java.awt.Color(7, 25, 82));
        matricula10.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula10.setForeground(new java.awt.Color(235, 244, 246));
        matricula10.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula10.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula10.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula10ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula10);
        matricula10.setBounds(40, 50, 400, 60);

        jLabel19.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(7, 25, 82));
        jLabel19.setText("NOME COMPLETO");
        jLabel19.setToolTipText("");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(40, 20, 230, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(110, 280, 1184, 600);

        jPanel3.setBackground(new java.awt.Color(235, 244, 246));
        jPanel3.setLayout(null);

        matricula3.setBackground(new java.awt.Color(7, 25, 82));
        matricula3.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula3.setForeground(new java.awt.Color(235, 244, 246));
        matricula3.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula3.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula3.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula3ActionPerformed(evt);
            }
        });
        jPanel3.add(matricula3);
        matricula3.setBounds(30, 30, 400, 60);

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(7, 25, 82));
        jLabel12.setText("CPF");
        jLabel12.setToolTipText("");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(30, 0, 230, 30);

        Procurar.setBackground(new java.awt.Color(7, 25, 82));
        Procurar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Procurar.setForeground(new java.awt.Color(235, 244, 246));
        Procurar.setText("PROCURAR");
        Procurar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarActionPerformed(evt);
            }
        });
        jPanel3.add(Procurar);
        Procurar.setBounds(730, 30, 400, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(110, 150, 1184, 104);

        jButton2.setBackground(new java.awt.Color(235, 244, 246));
        jButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(7, 25, 82));
        jButton2.setText("EXCLUIR");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 900, 150, 60);

        Voltar.setBackground(new java.awt.Color(7, 25, 82));
        Voltar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Voltar.setForeground(new java.awt.Color(235, 244, 246));
        Voltar.setText("VOLTAR");
        Voltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(Voltar);
        Voltar.setBounds(30, 910, 150, 60);

        jButton4.setBackground(new java.awt.Color(235, 244, 246));
        jButton4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(7, 25, 82));
        jButton4.setText("SALVAR");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(840, 900, 150, 60);

        jButton5.setBackground(new java.awt.Color(235, 244, 246));
        jButton5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(7, 25, 82));
        jButton5.setText("EDITAR");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(500, 900, 150, 60);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 244, 246));
        jLabel1.setText("CONSULTAR CADASTRO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 560, 62);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matricula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula3ActionPerformed

    private void matricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula1ActionPerformed

    private void matricula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula2ActionPerformed

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaActionPerformed

    private void matricula4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula4ActionPerformed

    private void matricula5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula5ActionPerformed

    private void matricula8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula8ActionPerformed

    private void matricula6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula6ActionPerformed

    private void matricula7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula7ActionPerformed

    private void matricula9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula9ActionPerformed

    private void matricula10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarActionPerformed

        
    }//GEN-LAST:event_ProcurarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        TELA_CLIENTE_MENU clit_menu = new TELA_CLIENTE_MENU();
        clit_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_CLIENTE_CONSULTAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Procurar;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField matricula1;
    private javax.swing.JTextField matricula10;
    private javax.swing.JTextField matricula2;
    private javax.swing.JTextField matricula3;
    private javax.swing.JTextField matricula4;
    private javax.swing.JTextField matricula5;
    private javax.swing.JTextField matricula6;
    private javax.swing.JTextField matricula7;
    private javax.swing.JTextField matricula8;
    private javax.swing.JTextField matricula9;
    // End of variables declaration//GEN-END:variables
}
