    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

import static com.mycompany.z_tintas.Classe_funcionario.buscarFuncionario;
import static com.mycompany.z_tintas.Classe_funcionario.excluirFuncionario;
import static com.mycompany.z_tintas.Classe_funcionario.salvarAlteracoes;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class TELA_FUNCIONARIO_CONSULTA extends javax.swing.JFrame {

    /**
     * Creates new form TELA_FUNCIONARIO_CONSULTA
     */
    public TELA_FUNCIONARIO_CONSULTA() {
        initComponents();
        CargoFuncionario.setEditable(false);
        NomeFuncionario.setEditable(false);
        Excluir.setEnabled(false);
        Salvar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CargoFuncionario = new javax.swing.JTextField();
        NomeFuncionario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();
        PROCURAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Editar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        voltar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(235, 244, 246));
        jPanel3.setMaximumSize(new java.awt.Dimension(1184, 125));
        jPanel3.setMinimumSize(new java.awt.Dimension(1184, 125));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(7, 25, 82));
        jLabel3.setText("Cargo:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(720, 0, 290, 62);

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 25, 82));
        jLabel4.setText("Nome Completo:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 0, 290, 62);

        CargoFuncionario.setBackground(new java.awt.Color(7, 25, 82));
        CargoFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        CargoFuncionario.setForeground(new java.awt.Color(235, 244, 246));
        CargoFuncionario.setMaximumSize(new java.awt.Dimension(400, 60));
        CargoFuncionario.setMinimumSize(new java.awt.Dimension(400, 60));
        CargoFuncionario.setPreferredSize(new java.awt.Dimension(400, 50));
        CargoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoFuncionarioActionPerformed(evt);
            }
        });
        jPanel3.add(CargoFuncionario);
        CargoFuncionario.setBounds(720, 60, 400, 50);

        NomeFuncionario.setBackground(new java.awt.Color(7, 25, 82));
        NomeFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        NomeFuncionario.setForeground(new java.awt.Color(235, 244, 246));
        NomeFuncionario.setMaximumSize(new java.awt.Dimension(400, 60));
        NomeFuncionario.setMinimumSize(new java.awt.Dimension(400, 60));
        NomeFuncionario.setPreferredSize(new java.awt.Dimension(400, 60));
        NomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeFuncionarioActionPerformed(evt);
            }
        });
        jPanel3.add(NomeFuncionario);
        NomeFuncionario.setBounds(30, 60, 400, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(128, 505, 1184, 125);

        jPanel2.setBackground(new java.awt.Color(235, 244, 246));
        jPanel2.setMaximumSize(new java.awt.Dimension(1184, 125));
        jPanel2.setMinimumSize(new java.awt.Dimension(1184, 125));
        jPanel2.setPreferredSize(new java.awt.Dimension(1184, 125));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 25, 82));
        jLabel1.setText("Matrícula:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 0, 170, 62);

        matricula.setBackground(new java.awt.Color(7, 25, 82));
        matricula.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula.setForeground(new java.awt.Color(235, 244, 246));
        matricula.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });
        jPanel2.add(matricula);
        matricula.setBounds(30, 60, 400, 50);

        PROCURAR.setBackground(new java.awt.Color(7, 25, 82));
        PROCURAR.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        PROCURAR.setForeground(new java.awt.Color(235, 244, 246));
        PROCURAR.setText("PROCURAR");
        PROCURAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PROCURAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROCURARActionPerformed(evt);
            }
        });
        jPanel2.add(PROCURAR);
        PROCURAR.setBounds(920, 30, 160, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(128, 330, 1184, 125);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 244, 246));
        jLabel2.setText("Consultar Funcionário");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(25, 25, 500, 62);

        Editar.setBackground(new java.awt.Color(235, 244, 246));
        Editar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Editar.setForeground(new java.awt.Color(7, 25, 82));
        Editar.setText("EDITAR");
        Editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPanel1.add(Editar);
        Editar.setBounds(500, 700, 150, 60);

        Excluir.setBackground(new java.awt.Color(235, 244, 246));
        Excluir.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Excluir.setForeground(new java.awt.Color(7, 25, 82));
        Excluir.setText("EXCLUIR");
        Excluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(Excluir);
        Excluir.setBounds(670, 700, 150, 60);

        Salvar.setBackground(new java.awt.Color(235, 244, 246));
        Salvar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Salvar.setForeground(new java.awt.Color(7, 25, 82));
        Salvar.setText("SALVAR");
        Salvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        jPanel1.add(Salvar);
        Salvar.setBounds(840, 700, 150, 60);

        voltar1.setBackground(new java.awt.Color(7, 25, 82));
        voltar1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        voltar1.setForeground(new java.awt.Color(235, 244, 246));
        voltar1.setText("VOLTAR");
        voltar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1ActionPerformed(evt);
            }
        });
        jPanel1.add(voltar1);
        voltar1.setBounds(1120, 50, 150, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PROCURARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROCURARActionPerformed
        // TODO add your handling code here:
        if(this.matricula.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O CAMPO DE MATRICULA É OBRIGATORIO");
        }else{
            int matricula= Integer.parseInt(this.matricula.getText());
            buscarFuncionario(matricula,NomeFuncionario,CargoFuncionario);
        }

    }//GEN-LAST:event_PROCURARActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
        CargoFuncionario.setEditable(true);
        NomeFuncionario.setEditable(true);
        Excluir.setEnabled(true);
        Salvar.setEnabled(true);        
    }//GEN-LAST:event_EditarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
        if(this.matricula.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O CAMPO DE MATRICULA É OBRIGATORIO");
        }else{
            int matricula= Integer.parseInt(this.matricula.getText());
            excluirFuncionario(matricula);
        }
        Excluir.setEnabled(false);
        Salvar.setEnabled(false);
    }//GEN-LAST:event_ExcluirActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        if(this.matricula.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O CAMPO DE MATRICULA É OBRIGATORIO");
        }else{
            int matricula= Integer.parseInt(this.matricula.getText());
            salvarAlteracoes(matricula,NomeFuncionario,CargoFuncionario);
        }
        Excluir.setEnabled(false);
        Salvar.setEnabled(false);
    }//GEN-LAST:event_SalvarActionPerformed

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaActionPerformed

    private void CargoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoFuncionarioActionPerformed
                
    }//GEN-LAST:event_CargoFuncionarioActionPerformed

    private void NomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeFuncionarioActionPerformed
                        
    }//GEN-LAST:event_NomeFuncionarioActionPerformed

    private void voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar1ActionPerformed
        // TODO add your handling code here:
        TELA_FUNCIONARIO_MENU func_menu = new TELA_FUNCIONARIO_MENU();
        func_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_FUNCIONARIO_CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_FUNCIONARIO_CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_FUNCIONARIO_CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_FUNCIONARIO_CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_FUNCIONARIO_CONSULTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CargoFuncionario;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JTextField NomeFuncionario;
    private javax.swing.JButton PROCURAR;
    private javax.swing.JButton Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField matricula;
    private javax.swing.JButton voltar1;
    // End of variables declaration//GEN-END:variables
}
