/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author Gabriel
 */
public class TELA_ESTOQUE_MENU extends javax.swing.JFrame {

    /**
     * Creates new form TELA_ESTOQUE_MENU
     */
    public TELA_ESTOQUE_MENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BT_CONSULTAR_ESTOQUE = new javax.swing.JButton();
        BT_CADASTRAR_ITEM = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 244, 246));
        jLabel1.setText("ESTOQUE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 300, 62);

        BT_CONSULTAR_ESTOQUE.setBackground(new java.awt.Color(235, 244, 246));
        BT_CONSULTAR_ESTOQUE.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        BT_CONSULTAR_ESTOQUE.setForeground(new java.awt.Color(7, 25, 82));
        BT_CONSULTAR_ESTOQUE.setText("CONSULTAR ITEM");
        BT_CONSULTAR_ESTOQUE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BT_CONSULTAR_ESTOQUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CONSULTAR_ESTOQUEActionPerformed(evt);
            }
        });
        jPanel1.add(BT_CONSULTAR_ESTOQUE);
        BT_CONSULTAR_ESTOQUE.setBounds(115, 329, 700, 160);

        BT_CADASTRAR_ITEM.setBackground(new java.awt.Color(235, 244, 246));
        BT_CADASTRAR_ITEM.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        BT_CADASTRAR_ITEM.setForeground(new java.awt.Color(7, 25, 82));
        BT_CADASTRAR_ITEM.setText("CADASTRAR NOVO ITEM");
        BT_CADASTRAR_ITEM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BT_CADASTRAR_ITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CADASTRAR_ITEMActionPerformed(evt);
            }
        });
        jPanel1.add(BT_CADASTRAR_ITEM);
        BT_CADASTRAR_ITEM.setBounds(115, 539, 700, 160);

        Voltar.setBackground(new java.awt.Color(7, 25, 82));
        Voltar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Voltar.setForeground(new java.awt.Color(235, 244, 246));
        Voltar.setText("VOLTAR");
        Voltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(Voltar);
        Voltar.setBounds(850, 590, 150, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_CONSULTAR_ESTOQUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CONSULTAR_ESTOQUEActionPerformed
        TELA_ESTOQUE_CONSULTAR estoque_consulta = new TELA_ESTOQUE_CONSULTAR();
        estoque_consulta.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BT_CONSULTAR_ESTOQUEActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        TELA_MENU_PRINCIPAL menu = new TELA_MENU_PRINCIPAL();
        menu.setVisible(true);
        dispose();

    }//GEN-LAST:event_VoltarActionPerformed

    private void BT_CADASTRAR_ITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CADASTRAR_ITEMActionPerformed
        // TODO add your handling code here:
        TELA_ESTOQUE_CADASTRO estoque_cadastro = new TELA_ESTOQUE_CADASTRO();
        estoque_cadastro.setVisible(true);
        dispose();
    }//GEN-LAST:event_BT_CADASTRAR_ITEMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_ESTOQUE_MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_CADASTRAR_ITEM;
    private javax.swing.JButton BT_CONSULTAR_ESTOQUE;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
