/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.z_tintas;

/**
 *
 * @author m.targa
 */
public class TELA_ESTOQUE_CONSULTAR extends javax.swing.JFrame {

    /** Creates new form TELA_ESTOQUE_CONSULTAR */
    public TELA_ESTOQUE_CONSULTAR() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        matricula6 = new javax.swing.JTextField();
        matricula8 = new javax.swing.JTextField();
        matricula9 = new javax.swing.JTextField();
        matricula10 = new javax.swing.JTextField();
        matricula11 = new javax.swing.JTextField();
        ENTRAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BT_VOLTAR_ESTOQUE_CONSULTA = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(235, 244, 246));
        jPanel2.setMaximumSize(new java.awt.Dimension(1377, 660));
        jPanel2.setMinimumSize(new java.awt.Dimension(1377, 660));
        jPanel2.setPreferredSize(new java.awt.Dimension(1377, 660));
        jPanel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(7, 25, 82));
        jLabel12.setText("MARCA");
        jLabel12.setToolTipText("");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(530, 20, 100, 30);

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(7, 25, 82));
        jLabel13.setText("CÓDIGO HEX");
        jLabel13.setToolTipText("");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(970, 20, 160, 30);

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(7, 25, 82));
        jLabel14.setText("TAMANHO");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(760, 20, 140, 30);

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(7, 25, 82));
        jLabel15.setText("NOME");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(240, 20, 80, 30);

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(7, 25, 82));
        jLabel16.setText("CÓDIGO");
        jLabel16.setToolTipText("");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 20, 100, 30);

        matricula6.setBackground(new java.awt.Color(7, 25, 82));
        matricula6.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula6.setForeground(new java.awt.Color(235, 244, 246));
        matricula6.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula6.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula6.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula6ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula6);
        matricula6.setBounds(760, 55, 160, 60);

        matricula8.setBackground(new java.awt.Color(7, 25, 82));
        matricula8.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula8.setForeground(new java.awt.Color(235, 244, 246));
        matricula8.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula8.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula8.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula8ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula8);
        matricula8.setBounds(530, 55, 200, 60);

        matricula9.setBackground(new java.awt.Color(7, 25, 82));
        matricula9.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula9.setForeground(new java.awt.Color(235, 244, 246));
        matricula9.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula9.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula9.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula9ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula9);
        matricula9.setBounds(240, 55, 250, 60);

        matricula10.setBackground(new java.awt.Color(7, 25, 82));
        matricula10.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula10.setForeground(new java.awt.Color(235, 244, 246));
        matricula10.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula10.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula10.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula10ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula10);
        matricula10.setBounds(30, 55, 160, 60);

        matricula11.setBackground(new java.awt.Color(7, 25, 82));
        matricula11.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula11.setForeground(new java.awt.Color(235, 244, 246));
        matricula11.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula11.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula11.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula11ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula11);
        matricula11.setBounds(970, 55, 160, 60);

        ENTRAR.setBackground(new java.awt.Color(7, 25, 82));
        ENTRAR.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        ENTRAR.setForeground(new java.awt.Color(235, 244, 246));
        ENTRAR.setText("BUSCAR");
        ENTRAR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTRARActionPerformed(evt);
            }
        });
        jPanel2.add(ENTRAR);
        ENTRAR.setBounds(1170, 60, 180, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOME", "MARCA", "TAMANHO", "CÓDIGO/HEX"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 190, 1320, 402);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 230, 1377, 660);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 244, 246));
        jLabel1.setText("CONSULTAR ESTOQUE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 520, 62);

        BT_VOLTAR_ESTOQUE_CONSULTA.setBackground(new java.awt.Color(7, 25, 82));
        BT_VOLTAR_ESTOQUE_CONSULTA.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        BT_VOLTAR_ESTOQUE_CONSULTA.setForeground(new java.awt.Color(235, 244, 246));
        BT_VOLTAR_ESTOQUE_CONSULTA.setText("VOLTAR");
        BT_VOLTAR_ESTOQUE_CONSULTA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BT_VOLTAR_ESTOQUE_CONSULTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_VOLTAR_ESTOQUE_CONSULTAActionPerformed(evt);
            }
        });
        jPanel1.add(BT_VOLTAR_ESTOQUE_CONSULTA);
        BT_VOLTAR_ESTOQUE_CONSULTA.setBounds(25, 900, 150, 60);

        jButton5.setBackground(new java.awt.Color(235, 244, 246));
        jButton5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(7, 25, 82));
        jButton5.setText("EDITAR");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(500, 900, 150, 60);

        jButton2.setBackground(new java.awt.Color(235, 244, 246));
        jButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(7, 25, 82));
        jButton2.setText("EXCLUIR");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 900, 150, 60);

        jButton4.setBackground(new java.awt.Color(235, 244, 246));
        jButton4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(7, 25, 82));
        jButton4.setText("SALVAR");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(840, 900, 150, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matricula6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula6ActionPerformed

    private void matricula8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula8ActionPerformed

    private void matricula9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula9ActionPerformed

    private void matricula10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula10ActionPerformed

    private void matricula11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula11ActionPerformed

    private void ENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTRARActionPerformed
        TELA_MENU_PRINCIPAL menu = new TELA_MENU_PRINCIPAL();
        menu.setVisible(true);
    }//GEN-LAST:event_ENTRARActionPerformed

    private void BT_VOLTAR_ESTOQUE_CONSULTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_VOLTAR_ESTOQUE_CONSULTAActionPerformed
        // TODO add your handling code here:
        TELA_ESTOQUE_MENU estoque_menu = new TELA_ESTOQUE_MENU();       
        estoque_menu.setVisible(true);
        dispose();

    }//GEN-LAST:event_BT_VOLTAR_ESTOQUE_CONSULTAActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_ESTOQUE_CONSULTAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_VOLTAR_ESTOQUE_CONSULTA;
    private javax.swing.JButton ENTRAR;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField matricula10;
    private javax.swing.JTextField matricula11;
    private javax.swing.JTextField matricula6;
    private javax.swing.JTextField matricula8;
    private javax.swing.JTextField matricula9;
    // End of variables declaration//GEN-END:variables

}
