/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

import static com.mycompany.z_tintas.Classe_cliente.excluirCliente;
import static com.mycompany.z_tintas.Classe_cliente.buscarCliente;
import static com.mycompany.z_tintas.Classe_cliente.salvarAlteracoescli;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Matheus
 */
public class TELA_CLIENTE_CONSULTAR extends javax.swing.JFrame {

    /**
     * Creates new form TELA_CLIENTE_CONSULTAR
     */
    public TELA_CLIENTE_CONSULTAR() {
        initComponents();
        nomeCompleto.setEditable(false);
        dt_nasc.setEditable(false);
        cpf_texto.setEditable(false);
        telefone.setEditable(false);       
        cep.setEditable(false);
        rua.setEditable(false);
        uf.setEditable(false);
        cidade.setEditable(false);
        bairro.setEditable(false);
        numero_Casa.setEditable(false);
        Excluir.setEnabled(false);
        Salvar.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dt_nasc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cpf_texto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        bairro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        uf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        numero_Casa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        nomeCompleto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Cpf_busca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Procurar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(235, 244, 246));
        jPanel2.setLayout(null);

        dt_nasc.setBackground(new java.awt.Color(7, 25, 82));
        dt_nasc.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        dt_nasc.setForeground(new java.awt.Color(235, 244, 246));
        dt_nasc.setMaximumSize(new java.awt.Dimension(400, 60));
        dt_nasc.setMinimumSize(new java.awt.Dimension(400, 60));
        dt_nasc.setPreferredSize(new java.awt.Dimension(400, 60));
        dt_nasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_nascActionPerformed(evt);
            }
        });
        jPanel2.add(dt_nasc);
        dt_nasc.setBounds(520, 50, 400, 60);

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(7, 25, 82));
        jLabel9.setText("DATA DE NASCIMENTO");
        jLabel9.setToolTipText("");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(520, 20, 290, 30);

        cpf_texto.setBackground(new java.awt.Color(7, 25, 82));
        cpf_texto.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        cpf_texto.setForeground(new java.awt.Color(235, 244, 246));
        cpf_texto.setMaximumSize(new java.awt.Dimension(400, 60));
        cpf_texto.setMinimumSize(new java.awt.Dimension(400, 60));
        cpf_texto.setPreferredSize(new java.awt.Dimension(400, 60));
        cpf_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf_textoActionPerformed(evt);
            }
        });
        jPanel2.add(cpf_texto);
        cpf_texto.setBounds(40, 150, 400, 60);

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(7, 25, 82));
        jLabel10.setText("CPF/CNPJ");
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 120, 120, 30);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 320, 1290, 20);

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(7, 25, 82));
        jLabel11.setText("ENDEREÇO");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 330, 140, 30);

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(7, 25, 82));
        jLabel13.setText("CEP");
        jLabel13.setToolTipText("");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(40, 370, 120, 30);

        cep.setBackground(new java.awt.Color(7, 25, 82));
        cep.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        cep.setForeground(new java.awt.Color(235, 244, 246));
        cep.setMaximumSize(new java.awt.Dimension(400, 60));
        cep.setMinimumSize(new java.awt.Dimension(400, 60));
        cep.setPreferredSize(new java.awt.Dimension(400, 60));
        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });
        jPanel2.add(cep);
        cep.setBounds(40, 400, 400, 60);

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(7, 25, 82));
        jLabel14.setText("CIDADE");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 470, 120, 30);

        cidade.setBackground(new java.awt.Color(7, 25, 82));
        cidade.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        cidade.setForeground(new java.awt.Color(235, 244, 246));
        cidade.setMaximumSize(new java.awt.Dimension(400, 60));
        cidade.setMinimumSize(new java.awt.Dimension(400, 60));
        cidade.setPreferredSize(new java.awt.Dimension(400, 60));
        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });
        jPanel2.add(cidade);
        cidade.setBounds(40, 500, 400, 60);

        bairro.setBackground(new java.awt.Color(7, 25, 82));
        bairro.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        bairro.setForeground(new java.awt.Color(235, 244, 246));
        bairro.setMaximumSize(new java.awt.Dimension(400, 60));
        bairro.setMinimumSize(new java.awt.Dimension(400, 60));
        bairro.setPreferredSize(new java.awt.Dimension(400, 60));
        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });
        jPanel2.add(bairro);
        bairro.setBounds(470, 500, 400, 60);

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(7, 25, 82));
        jLabel17.setText("BAIRRO");
        jLabel17.setToolTipText("");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(470, 470, 120, 30);

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(7, 25, 82));
        jLabel15.setText("RUA");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(470, 370, 120, 30);

        rua.setBackground(new java.awt.Color(7, 25, 82));
        rua.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        rua.setForeground(new java.awt.Color(235, 244, 246));
        rua.setMaximumSize(new java.awt.Dimension(400, 60));
        rua.setMinimumSize(new java.awt.Dimension(400, 60));
        rua.setPreferredSize(new java.awt.Dimension(400, 60));
        rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaActionPerformed(evt);
            }
        });
        jPanel2.add(rua);
        rua.setBounds(470, 400, 400, 60);

        uf.setBackground(new java.awt.Color(7, 25, 82));
        uf.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        uf.setForeground(new java.awt.Color(235, 244, 246));
        uf.setMaximumSize(new java.awt.Dimension(400, 60));
        uf.setMinimumSize(new java.awt.Dimension(400, 60));
        uf.setPreferredSize(new java.awt.Dimension(400, 60));
        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });
        jPanel2.add(uf);
        uf.setBounds(900, 400, 150, 60);

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(7, 25, 82));
        jLabel16.setText("UF");
        jLabel16.setToolTipText("");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(900, 370, 120, 30);

        numero_Casa.setBackground(new java.awt.Color(7, 25, 82));
        numero_Casa.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        numero_Casa.setForeground(new java.awt.Color(235, 244, 246));
        numero_Casa.setMaximumSize(new java.awt.Dimension(400, 60));
        numero_Casa.setMinimumSize(new java.awt.Dimension(400, 60));
        numero_Casa.setPreferredSize(new java.awt.Dimension(400, 60));
        numero_Casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_CasaActionPerformed(evt);
            }
        });
        jPanel2.add(numero_Casa);
        numero_Casa.setBounds(900, 500, 150, 60);

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(7, 25, 82));
        jLabel18.setText("NÚMERO");
        jLabel18.setToolTipText("");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(900, 470, 120, 30);

        nomeCompleto.setBackground(new java.awt.Color(7, 25, 82));
        nomeCompleto.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        nomeCompleto.setForeground(new java.awt.Color(235, 244, 246));
        nomeCompleto.setMaximumSize(new java.awt.Dimension(400, 60));
        nomeCompleto.setMinimumSize(new java.awt.Dimension(400, 60));
        nomeCompleto.setPreferredSize(new java.awt.Dimension(400, 60));
        nomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCompletoActionPerformed(evt);
            }
        });
        jPanel2.add(nomeCompleto);
        nomeCompleto.setBounds(40, 50, 400, 60);

        jLabel19.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(7, 25, 82));
        jLabel19.setText("NOME COMPLETO");
        jLabel19.setToolTipText("");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(40, 20, 230, 30);

        jLabel20.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(7, 25, 82));
        jLabel20.setText("TELEFONE");
        jLabel20.setToolTipText("");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(520, 120, 290, 30);

        telefone.setBackground(new java.awt.Color(7, 25, 82));
        telefone.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        telefone.setForeground(new java.awt.Color(235, 244, 246));
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        jPanel2.add(telefone);
        telefone.setBounds(520, 150, 400, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(110, 280, 1184, 600);

        jPanel3.setBackground(new java.awt.Color(235, 244, 246));
        jPanel3.setLayout(null);

        Cpf_busca.setBackground(new java.awt.Color(7, 25, 82));
        Cpf_busca.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        Cpf_busca.setForeground(new java.awt.Color(235, 244, 246));
        Cpf_busca.setMaximumSize(new java.awt.Dimension(400, 60));
        Cpf_busca.setMinimumSize(new java.awt.Dimension(400, 60));
        Cpf_busca.setPreferredSize(new java.awt.Dimension(400, 60));
        Cpf_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cpf_buscaActionPerformed(evt);
            }
        });
        jPanel3.add(Cpf_busca);
        Cpf_busca.setBounds(30, 30, 400, 60);

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(7, 25, 82));
        jLabel12.setText("CPF");
        jLabel12.setToolTipText("");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(30, 0, 230, 30);

        Procurar.setBackground(new java.awt.Color(7, 25, 82));
        Procurar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Procurar.setForeground(new java.awt.Color(235, 244, 246));
        Procurar.setText("PROCURAR");
        Procurar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarActionPerformed(evt);
            }
        });
        jPanel3.add(Procurar);
        Procurar.setBounds(730, 30, 400, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(110, 150, 1184, 104);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 244, 246));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Identificador consultar cadastro f.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 560, 88);

        jLabel2.setBackground(new java.awt.Color(7, 25, 82));
        jLabel2.setForeground(new java.awt.Color(7, 25, 82));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LOGO ZTINTAS.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1265, 25, 150, 150);

        Voltar.setBackground(new java.awt.Color(7, 25, 82));
        Voltar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Voltar.setForeground(new java.awt.Color(7, 25, 82));
        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voltarr.png"))); // NOI18N
        Voltar.setBorder(null);
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(Voltar);
        Voltar.setBounds(25, 900, 90, 90);

        Editar.setBackground(new java.awt.Color(235, 244, 246));
        Editar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Editar.setForeground(new java.awt.Color(7, 25, 82));
        Editar.setText("EDITAR");
        Editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPanel1.add(Editar);
        Editar.setBounds(480, 900, 150, 60);

        Excluir.setBackground(new java.awt.Color(235, 244, 246));
        Excluir.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Excluir.setForeground(new java.awt.Color(7, 25, 82));
        Excluir.setText("EXCLUIR");
        Excluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(Excluir);
        Excluir.setBounds(650, 900, 150, 60);

        Salvar.setBackground(new java.awt.Color(235, 244, 246));
        Salvar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Salvar.setForeground(new java.awt.Color(7, 25, 82));
        Salvar.setText("SALVAR");
        Salvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        jPanel1.add(Salvar);
        Salvar.setBounds(820, 900, 150, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cpf_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cpf_buscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cpf_buscaActionPerformed

    private void dt_nascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_nascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dt_nascActionPerformed

    private void cpf_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf_textoActionPerformed

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeActionPerformed

    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroActionPerformed

    private void ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed

    private void numero_CasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_CasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_CasaActionPerformed

    private void nomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCompletoActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if(this.Cpf_busca.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O CAMPO DE CPF É OBRIGATORIO");
        }else{
            String cpf = Cpf_busca.getText();
            excluirCliente(cpf);
        }
        Excluir.setEnabled(false);
        Salvar.setEnabled(false);

        
    }//GEN-LAST:event_ExcluirActionPerformed

    private void ProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarActionPerformed
        if(this.Cpf_busca.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O CAMPO DE MATRICULA É OBRIGATORIO");
        }else{
            String cpf = Cpf_busca.getText();
            buscarCliente(cpf,nomeCompleto,dt_nasc,cpf_texto,telefone,cep,rua,uf,cidade,bairro,numero_Casa);
        }        
    }//GEN-LAST:event_ProcurarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        TELA_CLIENTE_MENU clit_menu = new TELA_CLIENTE_MENU();
        clit_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        if(this.Cpf_busca.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O CAMPO DE MATRICULA É OBRIGATORIO");
        }else{
            String cpf = Cpf_busca.getText();
            salvarAlteracoescli(cpf,nomeCompleto,dt_nasc,cpf_texto,telefone,cep,uf,cidade,rua,numero_Casa,bairro);
        }
        Excluir.setEnabled(false);
        Salvar.setEnabled(false);
    }//GEN-LAST:event_SalvarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        nomeCompleto.setEditable(true);
        dt_nasc.setEditable(true);
        cpf_texto.setEditable(true);
        telefone.setEditable(true);
        cep.setEditable(true);
        rua.setEditable(true);
        uf.setEditable(true);
        cidade.setEditable(true);
        bairro.setEditable(true);
        numero_Casa.setEditable(true);
        Excluir.setEnabled(true);
        Salvar.setEnabled(true);
        
    }//GEN-LAST:event_EditarActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_CLIENTE_CONSULTAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cpf_busca;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Procurar;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cpf_texto;
    private javax.swing.JTextField dt_nasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nomeCompleto;
    private javax.swing.JTextField numero_Casa;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField telefone;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables

   

    
}
