/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

import static com.mycompany.z_tintas.Classe_cliente.inserirCliente;
import javax.swing.JOptionPane;
/**
 *
 * @author Matheus
 */
public class TELA_CLIENTE_CADASTRO extends javax.swing.JFrame {

    /**
     * Creates new form TELA_CLIENTE_CADASTRO
     */
    public TELA_CLIENTE_CADASTRO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        data_nasc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        uf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        realizar_cadastro_cliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(235, 244, 246));
        jPanel2.setMaximumSize(new java.awt.Dimension(1290, 676));
        jPanel2.setMinimumSize(new java.awt.Dimension(1290, 676));
        jPanel2.setPreferredSize(new java.awt.Dimension(1290, 676));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(7, 25, 82));
        jLabel9.setText("DATA DE NASCIMENTO");
        jLabel9.setToolTipText("");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(520, 20, 290, 30);

        data_nasc.setBackground(new java.awt.Color(7, 25, 82));
        data_nasc.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        data_nasc.setForeground(new java.awt.Color(235, 244, 246));
        data_nasc.setMaximumSize(new java.awt.Dimension(400, 60));
        data_nasc.setMinimumSize(new java.awt.Dimension(400, 60));
        data_nasc.setPreferredSize(new java.awt.Dimension(400, 60));
        data_nasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_nascActionPerformed(evt);
            }
        });
        jPanel2.add(data_nasc);
        data_nasc.setBounds(520, 50, 400, 60);

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(7, 25, 82));
        jLabel10.setText("CPF/CNPJ");
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 120, 120, 30);

        cpf.setBackground(new java.awt.Color(7, 25, 82));
        cpf.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        cpf.setForeground(new java.awt.Color(235, 244, 246));
        cpf.setMaximumSize(new java.awt.Dimension(400, 60));
        cpf.setMinimumSize(new java.awt.Dimension(400, 60));
        cpf.setPreferredSize(new java.awt.Dimension(400, 60));
        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        jPanel2.add(cpf);
        cpf.setBounds(40, 150, 400, 60);

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(7, 25, 82));
        jLabel11.setText("ENDEREÇO");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 330, 140, 30);

        nome.setBackground(new java.awt.Color(7, 25, 82));
        nome.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        nome.setForeground(new java.awt.Color(235, 244, 246));
        nome.setMaximumSize(new java.awt.Dimension(400, 60));
        nome.setMinimumSize(new java.awt.Dimension(400, 60));
        nome.setPreferredSize(new java.awt.Dimension(400, 60));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel2.add(nome);
        nome.setBounds(40, 50, 400, 60);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 320, 1290, 20);

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(7, 25, 82));
        jLabel12.setText("NOME COMPLETO");
        jLabel12.setToolTipText("");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(40, 20, 230, 30);

        cep.setBackground(new java.awt.Color(7, 25, 82));
        cep.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        cep.setForeground(new java.awt.Color(235, 244, 246));
        cep.setMaximumSize(new java.awt.Dimension(400, 60));
        cep.setMinimumSize(new java.awt.Dimension(400, 60));
        cep.setPreferredSize(new java.awt.Dimension(400, 60));
        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });
        jPanel2.add(cep);
        cep.setBounds(40, 400, 400, 60);

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(7, 25, 82));
        jLabel13.setText("CEP");
        jLabel13.setToolTipText("");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(40, 370, 120, 30);

        cidade.setBackground(new java.awt.Color(7, 25, 82));
        cidade.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        cidade.setForeground(new java.awt.Color(235, 244, 246));
        cidade.setMaximumSize(new java.awt.Dimension(400, 60));
        cidade.setMinimumSize(new java.awt.Dimension(400, 60));
        cidade.setPreferredSize(new java.awt.Dimension(400, 60));
        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });
        jPanel2.add(cidade);
        cidade.setBounds(40, 500, 400, 60);

        jLabel14.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(7, 25, 82));
        jLabel14.setText("CIDADE");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 470, 120, 30);

        rua.setBackground(new java.awt.Color(7, 25, 82));
        rua.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        rua.setForeground(new java.awt.Color(235, 244, 246));
        rua.setMaximumSize(new java.awt.Dimension(400, 60));
        rua.setMinimumSize(new java.awt.Dimension(400, 60));
        rua.setPreferredSize(new java.awt.Dimension(400, 60));
        rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaActionPerformed(evt);
            }
        });
        jPanel2.add(rua);
        rua.setBounds(470, 400, 400, 60);

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(7, 25, 82));
        jLabel15.setText("RUA");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(470, 370, 120, 30);

        uf.setBackground(new java.awt.Color(7, 25, 82));
        uf.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        uf.setForeground(new java.awt.Color(235, 244, 246));
        uf.setMaximumSize(new java.awt.Dimension(400, 60));
        uf.setMinimumSize(new java.awt.Dimension(400, 60));
        uf.setPreferredSize(new java.awt.Dimension(400, 60));
        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });
        jPanel2.add(uf);
        uf.setBounds(900, 400, 150, 60);

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(7, 25, 82));
        jLabel16.setText("UF");
        jLabel16.setToolTipText("");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(900, 370, 120, 30);

        bairro.setBackground(new java.awt.Color(7, 25, 82));
        bairro.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        bairro.setForeground(new java.awt.Color(235, 244, 246));
        bairro.setMaximumSize(new java.awt.Dimension(400, 60));
        bairro.setMinimumSize(new java.awt.Dimension(400, 60));
        bairro.setPreferredSize(new java.awt.Dimension(400, 60));
        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });
        jPanel2.add(bairro);
        bairro.setBounds(470, 500, 400, 60);

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(7, 25, 82));
        jLabel17.setText("BAIRRO");
        jLabel17.setToolTipText("");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(470, 470, 120, 30);

        numero.setBackground(new java.awt.Color(7, 25, 82));
        numero.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        numero.setForeground(new java.awt.Color(235, 244, 246));
        numero.setMaximumSize(new java.awt.Dimension(400, 60));
        numero.setMinimumSize(new java.awt.Dimension(400, 60));
        numero.setPreferredSize(new java.awt.Dimension(400, 60));
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        jPanel2.add(numero);
        numero.setBounds(900, 500, 150, 60);

        jLabel18.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(7, 25, 82));
        jLabel18.setText("NÚMERO");
        jLabel18.setToolTipText("");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(900, 470, 120, 30);

        realizar_cadastro_cliente.setBackground(new java.awt.Color(7, 25, 82));
        realizar_cadastro_cliente.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        realizar_cadastro_cliente.setForeground(new java.awt.Color(235, 244, 246));
        realizar_cadastro_cliente.setText("CADASTRAR");
        realizar_cadastro_cliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        realizar_cadastro_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizar_cadastro_clienteActionPerformed(evt);
            }
        });
        jPanel2.add(realizar_cadastro_cliente);
        realizar_cadastro_cliente.setBounds(430, 600, 400, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(75, 174, 1290, 676);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 244, 246));
        jLabel1.setText("CADASTRAR NOVO CLIENTE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 650, 62);

        Voltar.setBackground(new java.awt.Color(7, 25, 82));
        Voltar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        Voltar.setForeground(new java.awt.Color(235, 244, 246));
        Voltar.setText("VOLTAR");
        Voltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(Voltar);
        Voltar.setBounds(25, 900, 150, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void data_nascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_nascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_nascActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeActionPerformed

    private void ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed

    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void realizar_cadastro_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizar_cadastro_clienteActionPerformed
        boolean x = false;
        String cpf1 = cpf.getText().trim(); // Retira espaços em branco

        if (cpf1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O CPF É OBRIGATÓRIO");
        } else {
            if (cpf1.length() != 11) {
                JOptionPane.showMessageDialog(null, "O CPF precisa ter ONZE números!!!");
            } else {
                try {
                    Long.parseLong(cpf1); // Use Long para evitar overflow com 11 dígitos
                    x = true; // CPF válido
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "O CPF SÓ PODE CONTER NÚMEROS!!!");
                }
            }
        }
        

        
       /* String nome1 = nome.getText();
        
        String data_nasc1 = data_nasc.getText();
        String cep1 = cep.getText();
        String cidade1 = cidade.getText();
        String rua1 = rua.getText();
        String bairro1 = bairro.getText();
        String uf1 = uf.getText();
        String numero1 = numero.getText();*/
        Classe_cliente cliente_01 = new Classe_cliente(nome.getText(),data_nasc.getText(),cpf.getText(),cep.getText(),uf.getText(),cidade.getText(),rua.getText(),numero.getText(),bairro.getText());
        /*Classe_cliente cliente_01 = new Classe_cliente(nome1,data_nasc1,cpf1,cep1,uf1,cidade1,rua1,numero1,bairro1);*/
        if(x){
            inserirCliente(cliente_01);
        }
        
        
    }//GEN-LAST:event_realizar_cadastro_clienteActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        TELA_CLIENTE_MENU clit_menu = new TELA_CLIENTE_MENU();
        clit_menu.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_CLIENTE_CADASTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_CLIENTE_CADASTRO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField data_nasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JButton realizar_cadastro_cliente;
    private javax.swing.JTextField rua;
    private javax.swing.JTextField uf;
    // End of variables declaration//GEN-END:variables
}
