/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.z_tintas;

import static com.mycompany.z_tintas.Classe_produto.buscarProduto;
import static com.mycompany.z_tintas.Classe_produto.excluirProduto;
import static com.mycompany.z_tintas.Classe_produto.listarProdutos;
import static com.mycompany.z_tintas.Classe_produto.salvarAlteracoesProdutos;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author m.targa
 */
public class TELA_ESTOQUE_CONSULTAR extends javax.swing.JFrame {

    /** Creates new form TELA_ESTOQUE_CONSULTAR */
    public TELA_ESTOQUE_CONSULTAR() {
        initComponents();
        nomeProduto.setEditable(false);
        marcaProduto.setEditable(false);
        codHex.setEditable(false);
        PrecoProduto.setEditable(false);
        ExcluirProduto.setEnabled(false);
        SalvarProduto.setEnabled(false);
        
        // Altura das linhas
    tabela_produto.setRowHeight(30);

    // Largura das colunas
    tabela_produto.getColumnModel().getColumn(0).setPreferredWidth(100); // Matrícula
    tabela_produto.getColumnModel().getColumn(1).setPreferredWidth(300); // Nome
    tabela_produto.getColumnModel().getColumn(2).setPreferredWidth(200); // Cargo
    tabela_produto.getColumnModel().getColumn(3).setPreferredWidth(150); // Senha
    tabela_produto.getColumnModel().getColumn(4).setPreferredWidth(150);
    // Cabeçalho da tabela
    JTableHeader cabecalho = tabela_produto.getTableHeader();
    cabecalho.setFont(new Font("Segoe UI", Font.BOLD, 18));
    cabecalho.setBackground(new Color(7, 25, 82)); // Azul escuro
    cabecalho.setForeground(Color.WHITE);

    // Centralizar dados da coluna "Matrícula" e "Cargo"
    DefaultTableCellRenderer centro = new DefaultTableCellRenderer();
    centro.setHorizontalAlignment(SwingConstants.CENTER);

    tabela_produto.getColumnModel().getColumn(0).setCellRenderer(centro); 
    tabela_produto.getColumnModel().getColumn(1).setCellRenderer(centro); 
    tabela_produto.getColumnModel().getColumn(2).setCellRenderer(centro);
    tabela_produto.getColumnModel().getColumn(3).setCellRenderer(centro);
    tabela_produto.getColumnModel().getColumn(4).setCellRenderer(centro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        marcaProduto = new javax.swing.JTextField();
        nomeProduto = new javax.swing.JTextField();
        idProduto = new javax.swing.JTextField();
        codHex = new javax.swing.JTextField();
        BuscarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_produto = new javax.swing.JTable();
        PrecoProduto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        listar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EditarProduto = new javax.swing.JButton();
        ExcluirProduto = new javax.swing.JButton();
        SalvarProduto = new javax.swing.JButton();
        BT_VOLTAR_ESTOQUE_CONSULTA1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(235, 244, 246));
        jPanel2.setMaximumSize(new java.awt.Dimension(1377, 660));
        jPanel2.setMinimumSize(new java.awt.Dimension(1377, 660));
        jPanel2.setPreferredSize(new java.awt.Dimension(1377, 660));
        jPanel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(7, 25, 82));
        jLabel12.setText("MARCA");
        jLabel12.setToolTipText("");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(530, 20, 100, 30);

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(7, 25, 82));
        jLabel13.setText("CÓDIGO HEX");
        jLabel13.setToolTipText("");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(750, 20, 160, 30);

        jLabel15.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(7, 25, 82));
        jLabel15.setText("NOME");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(240, 20, 80, 30);

        jLabel16.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(7, 25, 82));
        jLabel16.setText("CÓDIGO");
        jLabel16.setToolTipText("");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 20, 100, 30);

        marcaProduto.setBackground(new java.awt.Color(7, 25, 82));
        marcaProduto.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        marcaProduto.setForeground(new java.awt.Color(235, 244, 246));
        marcaProduto.setMaximumSize(new java.awt.Dimension(400, 60));
        marcaProduto.setMinimumSize(new java.awt.Dimension(400, 60));
        marcaProduto.setPreferredSize(new java.awt.Dimension(400, 60));
        marcaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(marcaProduto);
        marcaProduto.setBounds(530, 55, 200, 60);

        nomeProduto.setBackground(new java.awt.Color(7, 25, 82));
        nomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        nomeProduto.setForeground(new java.awt.Color(235, 244, 246));
        nomeProduto.setMaximumSize(new java.awt.Dimension(400, 60));
        nomeProduto.setMinimumSize(new java.awt.Dimension(400, 60));
        nomeProduto.setPreferredSize(new java.awt.Dimension(400, 60));
        nomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(nomeProduto);
        nomeProduto.setBounds(240, 55, 250, 60);

        idProduto.setBackground(new java.awt.Color(7, 25, 82));
        idProduto.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        idProduto.setForeground(new java.awt.Color(235, 244, 246));
        idProduto.setMaximumSize(new java.awt.Dimension(400, 60));
        idProduto.setMinimumSize(new java.awt.Dimension(400, 60));
        idProduto.setPreferredSize(new java.awt.Dimension(400, 60));
        idProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(idProduto);
        idProduto.setBounds(30, 55, 160, 60);

        codHex.setBackground(new java.awt.Color(7, 25, 82));
        codHex.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        codHex.setForeground(new java.awt.Color(235, 244, 246));
        codHex.setMaximumSize(new java.awt.Dimension(400, 60));
        codHex.setMinimumSize(new java.awt.Dimension(400, 60));
        codHex.setPreferredSize(new java.awt.Dimension(400, 60));
        codHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codHexActionPerformed(evt);
            }
        });
        jPanel2.add(codHex);
        codHex.setBounds(750, 60, 160, 60);

        BuscarProduto.setBackground(new java.awt.Color(7, 25, 82));
        BuscarProduto.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        BuscarProduto.setForeground(new java.awt.Color(235, 244, 246));
        BuscarProduto.setText("BUSCAR");
        BuscarProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(BuscarProduto);
        BuscarProduto.setBounds(1170, 60, 180, 50);

        tabela_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME", "MARCA", "COD_HEX", "PRECO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_produto);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 160, 1320, 402);

        PrecoProduto.setBackground(new java.awt.Color(7, 25, 82));
        PrecoProduto.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        PrecoProduto.setForeground(new java.awt.Color(235, 244, 246));
        PrecoProduto.setMaximumSize(new java.awt.Dimension(400, 60));
        PrecoProduto.setMinimumSize(new java.awt.Dimension(400, 60));
        PrecoProduto.setPreferredSize(new java.awt.Dimension(400, 60));
        PrecoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(PrecoProduto);
        PrecoProduto.setBounds(950, 60, 160, 60);

        jLabel17.setFont(new java.awt.Font("Microsoft Tai Le", 1, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(7, 25, 82));
        jLabel17.setText("PREÇO R$:");
        jLabel17.setToolTipText("");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(950, 20, 140, 30);

        listar.setBackground(new java.awt.Color(7, 25, 82));
        listar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        listar.setForeground(new java.awt.Color(235, 244, 246));
        listar.setText("LISTAR");
        listar.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarActionPerformed(evt);
            }
        });
        jPanel2.add(listar);
        listar.setBounds(590, 580, 150, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 230, 1377, 660);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 244, 246));
        jLabel1.setText("CONSULTAR ESTOQUE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(25, 25, 520, 62);

        EditarProduto.setBackground(new java.awt.Color(235, 244, 246));
        EditarProduto.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        EditarProduto.setForeground(new java.awt.Color(7, 25, 82));
        EditarProduto.setText("EDITAR");
        EditarProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        EditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(EditarProduto);
        EditarProduto.setBounds(500, 900, 150, 60);

        ExcluirProduto.setBackground(new java.awt.Color(235, 244, 246));
        ExcluirProduto.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        ExcluirProduto.setForeground(new java.awt.Color(7, 25, 82));
        ExcluirProduto.setText("EXCLUIR");
        ExcluirProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        ExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(ExcluirProduto);
        ExcluirProduto.setBounds(670, 900, 150, 60);

        SalvarProduto.setBackground(new java.awt.Color(235, 244, 246));
        SalvarProduto.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        SalvarProduto.setForeground(new java.awt.Color(7, 25, 82));
        SalvarProduto.setText("SALVAR");
        SalvarProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        SalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(SalvarProduto);
        SalvarProduto.setBounds(840, 900, 150, 60);

        BT_VOLTAR_ESTOQUE_CONSULTA1.setBackground(new java.awt.Color(7, 25, 82));
        BT_VOLTAR_ESTOQUE_CONSULTA1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        BT_VOLTAR_ESTOQUE_CONSULTA1.setForeground(new java.awt.Color(235, 244, 246));
        BT_VOLTAR_ESTOQUE_CONSULTA1.setText("VOLTAR");
        BT_VOLTAR_ESTOQUE_CONSULTA1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        BT_VOLTAR_ESTOQUE_CONSULTA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_VOLTAR_ESTOQUE_CONSULTA1ActionPerformed(evt);
            }
        });
        jPanel1.add(BT_VOLTAR_ESTOQUE_CONSULTA1);
        BT_VOLTAR_ESTOQUE_CONSULTA1.setBounds(25, 900, 150, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marcaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaProdutoActionPerformed

    private void nomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdutoActionPerformed

    private void idProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProdutoActionPerformed

    private void codHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codHexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codHexActionPerformed

    private void BuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProdutoActionPerformed
        if(this.idProduto.getText().isEmpty()){
            nomeProduto.setEditable(false);
            marcaProduto.setEditable(false);
            codHex.setEditable(false);
            PrecoProduto.setEditable(false);
            ExcluirProduto.setEnabled(false);
            SalvarProduto.setEnabled(false);
            JOptionPane.showMessageDialog(null, "O CAMPO DE CÓDIGO É OBRIGATORIO");
        }else{
            buscarProduto( idProduto,nomeProduto,marcaProduto,codHex,PrecoProduto);
        }                
        
    }//GEN-LAST:event_BuscarProdutoActionPerformed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        // TODO add your handling code here:
            listarProdutos(tabela_produto);

    }//GEN-LAST:event_listarActionPerformed

    private void EditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarProdutoActionPerformed
        // TODO add your handling code here:
        nomeProduto.setEditable(true);
        marcaProduto.setEditable(true);
        codHex.setEditable(true);
        PrecoProduto.setEditable(true);
        ExcluirProduto.setEnabled(true);
        SalvarProduto.setEnabled(true);
    }//GEN-LAST:event_EditarProdutoActionPerformed

    private void ExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirProdutoActionPerformed
        excluirProduto(Integer.parseInt(idProduto.getText()));
        nomeProduto.setEditable(false);
        marcaProduto.setEditable(false);
        codHex.setEditable(false);
        PrecoProduto.setEditable(false);
        ExcluirProduto.setEnabled(false);
        SalvarProduto.setEnabled(false);
        
    }//GEN-LAST:event_ExcluirProdutoActionPerformed

    private void SalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarProdutoActionPerformed
        nomeProduto.setEditable(false);
        marcaProduto.setEditable(false);
        codHex.setEditable(false);
        PrecoProduto.setEditable(false);
        ExcluirProduto.setEnabled(false);
        SalvarProduto.setEnabled(false);
        salvarAlteracoesProdutos (idProduto, nomeProduto, marcaProduto,  codHex,  PrecoProduto);
    }//GEN-LAST:event_SalvarProdutoActionPerformed

    private void PrecoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoProdutoActionPerformed

    private void BT_VOLTAR_ESTOQUE_CONSULTA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_VOLTAR_ESTOQUE_CONSULTA1ActionPerformed
        // TODO add your handling code here:
        TELA_ESTOQUE_MENU estoque_menu = new TELA_ESTOQUE_MENU();               
        estoque_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BT_VOLTAR_ESTOQUE_CONSULTA1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_ESTOQUE_CONSULTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_ESTOQUE_CONSULTAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_VOLTAR_ESTOQUE_CONSULTA1;
    private javax.swing.JButton BuscarProduto;
    private javax.swing.JButton EditarProduto;
    private javax.swing.JButton ExcluirProduto;
    private javax.swing.JTextField PrecoProduto;
    private javax.swing.JButton SalvarProduto;
    private javax.swing.JTextField codHex;
    private javax.swing.JTextField idProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listar;
    private javax.swing.JTextField marcaProduto;
    private javax.swing.JTextField nomeProduto;
    private javax.swing.JTable tabela_produto;
    // End of variables declaration//GEN-END:variables

}
