    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.z_tintas;

/**
 *
 * @author Gabriel
 */
public class TELA_FUNCIONARIO_CONSULTA extends javax.swing.JFrame {

    /**
     * Creates new form TELA_FUNCIONARIO_CONSULTA
     */
    public TELA_FUNCIONARIO_CONSULTA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        matricula11 = new javax.swing.JTextField();
        matricula12 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula10 = new javax.swing.JTextField();
        PROCURAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        voltar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 1024));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(7, 25, 82));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(235, 244, 246));
        jPanel3.setMaximumSize(new java.awt.Dimension(1184, 125));
        jPanel3.setMinimumSize(new java.awt.Dimension(1184, 125));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(7, 25, 82));
        jLabel3.setText("Cargo:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(720, 0, 290, 62);

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 25, 82));
        jLabel4.setText("Nome Completo:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 0, 290, 62);

        matricula11.setBackground(new java.awt.Color(7, 25, 82));
        matricula11.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula11.setForeground(new java.awt.Color(235, 244, 246));
        matricula11.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula11.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula11.setPreferredSize(new java.awt.Dimension(400, 50));
        matricula11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula11ActionPerformed(evt);
            }
        });
        jPanel3.add(matricula11);
        matricula11.setBounds(720, 60, 400, 50);

        matricula12.setBackground(new java.awt.Color(7, 25, 82));
        matricula12.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula12.setForeground(new java.awt.Color(235, 244, 246));
        matricula12.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula12.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula12.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula12ActionPerformed(evt);
            }
        });
        jPanel3.add(matricula12);
        matricula12.setBounds(30, 60, 400, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(128, 505, 1184, 125);

        jPanel2.setBackground(new java.awt.Color(235, 244, 246));
        jPanel2.setMaximumSize(new java.awt.Dimension(1184, 125));
        jPanel2.setMinimumSize(new java.awt.Dimension(1184, 125));
        jPanel2.setPreferredSize(new java.awt.Dimension(1184, 125));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 25, 82));
        jLabel1.setText("Matrícula:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 0, 170, 62);

        matricula10.setBackground(new java.awt.Color(7, 25, 82));
        matricula10.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        matricula10.setForeground(new java.awt.Color(235, 244, 246));
        matricula10.setMaximumSize(new java.awt.Dimension(400, 60));
        matricula10.setMinimumSize(new java.awt.Dimension(400, 60));
        matricula10.setPreferredSize(new java.awt.Dimension(400, 60));
        matricula10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula10ActionPerformed(evt);
            }
        });
        jPanel2.add(matricula10);
        matricula10.setBounds(30, 60, 400, 50);

        PROCURAR.setBackground(new java.awt.Color(7, 25, 82));
        PROCURAR.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        PROCURAR.setForeground(new java.awt.Color(235, 244, 246));
        PROCURAR.setText("PROCURAR");
        PROCURAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PROCURAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROCURARActionPerformed(evt);
            }
        });
        jPanel2.add(PROCURAR);
        PROCURAR.setBounds(920, 30, 160, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(128, 330, 1184, 125);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 244, 246));
        jLabel2.setText("Consultar Funcionário");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(25, 25, 500, 62);

        jButton5.setBackground(new java.awt.Color(235, 244, 246));
        jButton5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(7, 25, 82));
        jButton5.setText("EDITAR");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(500, 700, 150, 60);

        jButton2.setBackground(new java.awt.Color(235, 244, 246));
        jButton2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(7, 25, 82));
        jButton2.setText("EXCLUIR");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 700, 150, 60);

        jButton4.setBackground(new java.awt.Color(235, 244, 246));
        jButton4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(7, 25, 82));
        jButton4.setText("SALVAR");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(840, 700, 150, 60);

        voltar1.setBackground(new java.awt.Color(7, 25, 82));
        voltar1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        voltar1.setForeground(new java.awt.Color(235, 244, 246));
        voltar1.setText("VOLTAR");
        voltar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1ActionPerformed(evt);
            }
        });
        jPanel1.add(voltar1);
        voltar1.setBounds(1120, 50, 150, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PROCURARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROCURARActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_PROCURARActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void matricula10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula10ActionPerformed

    private void matricula11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula11ActionPerformed

    private void matricula12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula12ActionPerformed

    private void voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar1ActionPerformed
        // TODO add your handling code here:
        TELA_FUNCIONARIO_MENU func_menu = new TELA_FUNCIONARIO_MENU();
        func_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_FUNCIONARIO_CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_FUNCIONARIO_CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_FUNCIONARIO_CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_FUNCIONARIO_CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_FUNCIONARIO_CONSULTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PROCURAR;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField matricula10;
    private javax.swing.JTextField matricula11;
    private javax.swing.JTextField matricula12;
    private javax.swing.JButton voltar1;
    // End of variables declaration//GEN-END:variables
}
